from elegant_tesla.youthful_booth import youthful_booth as youthful_booth1
from elegant_tesla.zen_pike import thirsty_knuth as thirsty_knuth1
from elegant_tesla.boring_boyd.agitated_goldberg import youthful_wescoff as youthful_wescoff1
from elegant_tesla.reverent_goldwasser.goofy_kepler import optimistic_hawking as optimistic_hawking1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
from peaceful_bohr.zen_pike.agitated_goldberg import hopeful_booth as hopeful_booth1
