from loving_visvesvaraya.confident_hoover.elegant_raman import infallible_joliot as infallible_joliot1
from loving_visvesvaraya.confident_hoover.adoring_hugle import infallible_joliot as infallible_joliot2
from loving_visvesvaraya.confident_hoover.hardcore_hopper import infallible_joliot as infallible_joliot3
from loving_visvesvaraya.confident_hoover import infallible_joliot as infallible_joliot4
from loving_visvesvaraya.confident_hoover.sad_carson import infallible_joliot as infallible_joliot5
from loving_visvesvaraya.confident_hoover.brave_nobel import infallible_joliot as infallible_joliot6
from loving_visvesvaraya.confident_hoover.eloquent_fermat import infallible_joliot as infallible_joliot7
