from loving_visvesvaraya.nostalgic_ardinghelli import pedantic_lamarr as pedantic_lamarr1
import reverent_fermi as reverent_fermi1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
import vigorous_thompson as vigorous_thompson1
