from elegant_tesla.zen_pike.optimistic_hawking import cranky_lamport as cranky_lamport1
from elegant_tesla.zen_pike import heuristic_babbage as heuristic_babbage1
from elegant_tesla.reverent_nightingale.vigorous_stallman.cranky_ramanujan import lucid_kalam as lucid_kalam1
from elegant_tesla.reverent_nightingale.vigorous_stallman.cranky_ramanujan.frosty_austin import goofy_bose as goofy_bose1
