from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.boring_boyd import hungry_johnson as hungry_johnson1
from elegant_tesla.boring_boyd.clever_raman import serene_mahavira as serene_mahavira1
from elegant_tesla.boring_boyd.clever_raman import zen_curie as zen_curie1
from peaceful_bohr import zen_curie as zen_curie2
from elegant_tesla.boring_boyd.clever_raman import vigorous_albattani as vigorous_albattani1
import vigorous_thompson as vigorous_thompson1
from peaceful_bohr.eloquent_liskov.boring_boyd.clever_raman import focused_mirzakhani as focused_mirzakhani2
