import silly_panini as silly_panini1
from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from elegant_tesla.boring_dijkstra import friendly_hodgkin as friendly_hodgkin1
from elegant_tesla.boring_dijkstra.optimistic_hawking import tender_ptolemy as tender_ptolemy1
