from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.cranky_goldwasser import confident_hoover as confident_hoover1
from elegant_tesla.cranky_goldwasser import relaxed_perlman as relaxed_perlman1
