import peaceful_turing as peaceful_turing1
from elegant_tesla.reverent_goldwasser.eloquent_borg import eloquent_borg as eloquent_borg1
from loving_visvesvaraya.lucid_shockley.nervous_banach.sad_murdock import fervent_swartz as fervent_swartz1
from loving_visvesvaraya.lucid_shockley.awesome_morse.hardcore_volhard import fervent_swartz as fervent_swartz2
from loving_visvesvaraya.lucid_shockley.awesome_morse.eager_lalande import fervent_swartz as fervent_swartz3
from elegant_tesla.cranky_goldwasser.lucid_shockley import serene_bose as serene_bose1
