from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from elegant_tesla.cranky_goldwasser.awesome_noyce import stoic_pike as stoic_pike1
from elegant_tesla.zen_pike import competent_jennings as competent_jennings1
from stupefied_gates import distracted_haibt as distracted_haibt1
from elegant_tesla.cranky_goldwasser.awesome_noyce import romantic_ramanujan as romantic_ramanujan1
