from elegant_tesla.zen_pike import elegant_bose as elegant_bose1
from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from elegant_tesla.youthful_booth import youthful_booth as youthful_booth1
from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from elegant_tesla.boring_dijkstra.optimistic_hawking.elegant_bose import nifty_murdock as nifty_murdock1
from elegant_tesla.boring_dijkstra import distracted_hawking as distracted_hawking1
from elegant_tesla.boring_dijkstra import goofy_swanson as goofy_swanson1
from elegant_tesla.boring_dijkstra import zen_pike as zen_pike1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
import jovial_swartz as jovial_swartz1
