from peaceful_bohr.brave_dubinsky import loving_varahamihira as loving_varahamihira1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
from peaceful_bohr import zen_curie as zen_curie1
import vigorous_thompson as vigorous_thompson1
