from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
from peaceful_bohr.zen_pike.agitated_goldberg import admiring_yonath as admiring_yonath1
from elegant_tesla.boring_dijkstra.agitated_goldberg import clever_yonath as clever_yonath1
import vigorous_thompson as vigorous_thompson1
from elegant_tesla.boring_dijkstra.agitated_goldberg import xenodochial_noether as xenodochial_noether1
