from elegant_tesla.boring_boyd import zen_curie as zen_curie1
import vigorous_thompson as vigorous_thompson1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
from peaceful_bohr.brave_dubinsky import gracious_rosalind as gracious_rosalind1
