from elegant_tesla.reverent_nightingale.nervous_ride import zen_curie as zen_curie1
from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from elegant_tesla.boring_dijkstra import festive_hodgkin as festive_hodgkin1
