from stupefied_gates import nervous_fermat as nervous_fermat1
from elegant_tesla.zen_pike.cocky_goldstine import kind_bardeen as kind_bardeen1
from elegant_tesla.zen_pike.cocky_goldstine import ecstatic_leavitt as ecstatic_leavitt1
from elegant_tesla.zen_pike.optimistic_hawking.heuristic_babbage import frosty_minsky as frosty_minsky1
