from elegant_tesla.clever_mestorf.vigorous_colden import awesome_morse as awesome_morse1
from peaceful_bohr.jovial_bell import angry_feynman as angry_feynman1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
