from elegant_tesla.boring_dijkstra import zen_curie as zen_curie1
from elegant_tesla.youthful_booth import youthful_booth as youthful_booth1
from elegant_tesla.zen_pike.optimistic_hawking import frosty_goldberg as frosty_goldberg1
from elegant_tesla.boring_dijkstra import zen_pike as zen_pike1
