from elegant_tesla.boring_dijkstra import objective_lamarr as objective_lamarr1
from elegant_tesla.boring_dijkstra import zen_curie as zen_curie1
from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from elegant_tesla.youthful_booth import youthful_booth as youthful_booth1
from peaceful_bohr.admiring_carson import zen_curie as zen_curie2
