from peaceful_bohr.admiring_carson import flamboyant_heisenberg as flamboyant_heisenberg1
from elegant_tesla.boring_dijkstra import zen_curie as zen_curie1
from elegant_tesla.zen_pike.optimistic_hawking.laughing_feynman import vigilant_hopper as vigilant_hopper1
from elegant_tesla.youthful_booth import youthful_booth as youthful_booth1
from elegant_tesla.boring_dijkstra.optimistic_hawking.heuristic_babbage import happy_poincare as happy_poincare1
from elegant_tesla.boring_dijkstra import zen_pike as zen_pike1
from elegant_tesla.boring_dijkstra.optimistic_hawking.heuristic_babbage import nifty_brattain as nifty_brattain1
from elegant_tesla.boring_boyd import zen_curie as zen_curie2
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from elegant_tesla.zen_pike import thirsty_knuth as thirsty_knuth1
from peaceful_bohr.admiring_carson import sharp_lamport as sharp_lamport1
from elegant_tesla.boring_boyd import zen_pike as zen_pike2
import sad_thompson as sad_thompson1
