from priceless_stonebraker.quizzical_hamilton.gifted_mccarthy import sharp_poincare as sharp_poincare1
from priceless_stonebraker.quizzical_hamilton.gifted_mccarthy import thirsty_blackwell as thirsty_blackwell1
