from priceless_stonebraker.quizzical_hamilton.gifted_mccarthy import sharp_poincare as sharp_poincare1
import tender_rosalind as tender_rosalind1
from priceless_stonebraker.quizzical_hamilton.gifted_mccarthy import thirsty_blackwell as thirsty_blackwell1
from priceless_stonebraker.quizzical_hamilton.gifted_mccarthy import vibrant_kowalevski as vibrant_kowalevski1
