from stupefied_gates import nervous_fermat as nervous_fermat1
from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from elegant_tesla.xenodochial_aryabhata.trusting_murdock import amazing_snyder as amazing_snyder1
