from peaceful_bohr.admiring_carson.loving_visvesvaraya.stupefied_sinoussi import zealous_shockley as zealous_shockley1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
from loving_visvesvaraya.stupefied_sinoussi import awesome_minsky as awesome_minsky1
from peaceful_bohr.admiring_carson.loving_visvesvaraya.stupefied_sinoussi import focused_mirzakhani as focused_mirzakhani2
