from peaceful_bohr.admiring_carson.loving_visvesvaraya.stupefied_sinoussi import zealous_shockley as zealous_shockley1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
from peaceful_bohr.admiring_carson.loving_visvesvaraya.stupefied_sinoussi import focused_mirzakhani as focused_mirzakhani2
from loving_visvesvaraya.stupefied_sinoussi import mystifying_poincare as mystifying_poincare1
