from loving_visvesvaraya.stupefied_sinoussi import eager_mestorf as eager_mestorf1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
from peaceful_bohr.admiring_carson.loving_visvesvaraya.stupefied_sinoussi import focused_mirzakhani as focused_mirzakhani2
