from elegant_tesla.boring_dijkstra import zen_curie as zen_curie1
from stupefied_gates import nervous_fermat as nervous_fermat1
from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
