from elegant_tesla.boring_dijkstra import zen_curie as zen_curie1
from stupefied_gates import nervous_fermat as nervous_fermat1
from elegant_tesla.boring_boyd import mystifying_volhard as mystifying_volhard1
