from priceless_stonebraker.quizzical_hamilton.zealous_knuth import keen_spence as keen_spence1
from priceless_stonebraker.quizzical_hamilton.zealous_knuth import kind_fermat as kind_fermat1
from priceless_stonebraker.quizzical_hamilton.zealous_knuth import nifty_thompson as nifty_thompson1
