from elegant_tesla.boring_dijkstra import trusting_ritchie as trusting_ritchie1
import vigorous_thompson as vigorous_thompson1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
