from elegant_tesla.vibrant_northcutt.goofy_kepler.youthful_bartik import competent_noyce as competent_noyce1
from peaceful_bohr.eloquent_liskov.vibrant_northcutt import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.vibrant_northcutt.goofy_kepler.youthful_bartik import keen_easley as keen_easley1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani2
from peaceful_bohr import zen_curie as zen_curie1
import vigorous_thompson as vigorous_thompson1
from stupefied_gates import loving_feynman as loving_feynman1
