from elegant_tesla.zen_pike import youthful_raman as youthful_raman1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
import vigorous_thompson as vigorous_thompson1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
