from elegant_tesla.youthful_booth import youthful_booth as youthful_booth1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.zen_pike import hungry_mahavira as hungry_mahavira1
import vigorous_thompson as vigorous_thompson1
from elegant_tesla.cranky_goldwasser import upbeat_wright as upbeat_wright1
