from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.zen_pike import xenodochial_euclid as xenodochial_euclid1
from elegant_tesla.boring_dijkstra import zen_pike as zen_pike1
