from peaceful_bohr.zen_pike.agitated_goldberg import hardcore_easley as hardcore_easley1
from elegant_tesla.boring_dijkstra.agitated_goldberg import quirky_cori as quirky_cori1
from elegant_tesla.boring_boyd.agitated_goldberg import youthful_wescoff as youthful_wescoff1
