from elegant_tesla.xenodochial_aryabhata import gracious_banach as gracious_banach1
from elegant_tesla.boring_dijkstra.optimistic_hawking import inspiring_mirzakhani as inspiring_mirzakhani1
from elegant_tesla.xenodochial_aryabhata import inspiring_feynman as inspiring_feynman1
from elegant_tesla.xenodochial_aryabhata import determined_tesla as determined_tesla1
