from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.xenodochial_aryabhata import suspicious_babbage as suspicious_babbage1
from peaceful_bohr import zen_curie as zen_curie1
from elegant_tesla.zen_pike import loving_pare as loving_pare1
import vigorous_thompson as vigorous_thompson1
