from elegant_tesla.vibrant_northcutt.goofy_kepler.elegant_darwin import ecstatic_tesla as ecstatic_tesla1
from elegant_tesla.boring_dijkstra.musing_fermi import optimistic_hawking as optimistic_hawking1
from elegant_tesla.vibrant_northcutt.goofy_kepler.elegant_darwin import optimistic_hawking as optimistic_hawking2
from elegant_tesla.vibrant_northcutt.goofy_kepler.elegant_darwin import boring_heisenberg as boring_heisenberg1
