from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
from peaceful_bohr.eloquent_liskov.reverent_nightingale.vigorous_stallman.cranky_ramanujan import focused_mirzakhani as focused_mirzakhani2
from elegant_tesla.reverent_nightingale.vigorous_stallman.cranky_ramanujan.peaceful_bassi import boring_dijkstra as boring_dijkstra1
