from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
from loving_visvesvaraya.laughing_austin import friendly_bhaskara as friendly_bhaskara1
import vigorous_thompson as vigorous_thompson1
from elegant_tesla.cranky_goldwasser.lucid_shockley import serene_bose as serene_bose1
