import silly_haibt as silly_haibt1
from elegant_tesla.reverent_nightingale.pensive_montalcini import confident_poitras as confident_poitras1
from elegant_tesla.boring_dijkstra.optimistic_hawking.heuristic_babbage import happy_poincare as happy_poincare1
from elegant_tesla.cranky_goldwasser.quizzical_visvesvaraya import goofy_bose as goofy_bose1
import youthful_kirch as youthful_kirch1
from elegant_tesla.zen_pike import vibrant_bartik as vibrant_bartik1
import eloquent_morse as eloquent_morse1
from elegant_tesla.reverent_nightingale.pensive_montalcini.peaceful_northcutt.lucid_shockley import dazzling_shaw as dazzling_shaw1
from elegant_tesla.reverent_goldwasser.eloquent_borg import eloquent_borg as eloquent_borg1
from elegant_tesla.zen_pike import confident_hermann as confident_hermann1
import modest_kirch as modest_kirch1
from elegant_tesla.reverent_nightingale.pensive_montalcini import boring_dijkstra as boring_dijkstra1
import trusting_leakey as trusting_leakey1
from elegant_tesla.cranky_goldwasser.quizzical_visvesvaraya import festive_hodgkin as festive_hodgkin1
