from elegant_tesla.reverent_goldwasser.eloquent_borg import eloquent_borg as eloquent_borg1
from elegant_tesla.reverent_nightingale.pensive_montalcini import confident_poitras as confident_poitras1
from elegant_tesla.boring_dijkstra.optimistic_hawking.heuristic_babbage import happy_poincare as happy_poincare1
from elegant_tesla.cranky_goldwasser.quizzical_visvesvaraya import goofy_bose as goofy_bose1
from elegant_tesla.cranky_goldwasser.quizzical_visvesvaraya import festive_hodgkin as festive_hodgkin1
from elegant_tesla.reverent_nightingale.pensive_montalcini import infallible_aryabhata as infallible_aryabhata1
from elegant_tesla.cranky_goldwasser.quizzical_visvesvaraya import infallible_aryabhata as infallible_aryabhata2
from elegant_tesla.cranky_goldwasser.quizzical_visvesvaraya import dazzling_shaw as dazzling_shaw1
