from stupefied_gates import nervous_fermat as nervous_fermat1
from elegant_tesla.boring_boyd.clever_raman import youthful_bhabha as youthful_bhabha1
from elegant_tesla.boring_boyd.clever_raman import zen_curie as zen_curie1
from elegant_tesla.boring_boyd import distracted_pike as distracted_pike1
