from peaceful_bohr.brave_dubinsky import jolly_austin as jolly_austin1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
from peaceful_bohr.zen_pike.relaxed_thompson import laughing_cray as laughing_cray1
from elegant_tesla.zen_pike.optimistic_hawking import jovial_dijkstra as jovial_dijkstra1
from peaceful_bohr.admiring_carson.reverent_nightingale.vigorous_stallman.cranky_ramanujan import focused_mirzakhani as focused_mirzakhani2
from elegant_tesla.reverent_nightingale.vigorous_stallman.cranky_ramanujan.relaxed_bhaskara import jolly_austin as jolly_austin2
