from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
from peaceful_bohr.admiring_carson.reverent_nightingale.vigorous_stallman.cranky_ramanujan import focused_mirzakhani as focused_mirzakhani2
import vigorous_thompson as vigorous_thompson1
