from elegant_tesla.reverent_goldwasser.goofy_kepler import frosty_mcclintock as frosty_mcclintock1
from peaceful_bohr.zen_pike import hardcore_jepsen as hardcore_jepsen1
from elegant_tesla.cranky_goldwasser.hopeful_feynman import confident_hoover as confident_hoover1
from peaceful_bohr.wizardly_jepsen import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.zen_pike import hardcore_morse as hardcore_morse1
from elegant_tesla.boring_boyd import zen_curie as zen_curie1
import vigorous_thompson as vigorous_thompson1
