import hardcore_hypatia as hardcore_hypatia1
from elegant_tesla.reverent_goldwasser.eloquent_borg import eloquent_borg as eloquent_borg1
from peaceful_bohr.jovial_bell import confident_turing as confident_turing1
from elegant_tesla.zen_pike import priceless_shannon as priceless_shannon1
from elegant_tesla.boring_dijkstra import goofy_swanson as goofy_swanson1
from peaceful_bohr.wizardly_jepsen import focused_mirzakhani as focused_mirzakhani1
import vigorous_thompson as vigorous_thompson1
