import hungry_neumann as hungry_neumann1
from elegant_tesla.reverent_goldwasser.eloquent_borg import eloquent_borg as eloquent_borg1
from loving_visvesvaraya.confident_hoover.adoring_hugle import compassionate_johnson as compassionate_johnson1
