from peaceful_bohr.eloquent_chandrasekhar import focused_mirzakhani as focused_mirzakhani1
from peaceful_bohr.zen_pike import determined_mirzakhani as determined_mirzakhani1
import vigorous_thompson as vigorous_thompson1
from stupefied_gates import quirky_sammet as quirky_sammet1
from peaceful_bohr.friendly_lalande import relaxed_khorana as relaxed_khorana1
