from elegant_tesla.reverent_bose import reverent_bose as reverent_bose1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
