from elegant_tesla.cranky_goldwasser import hardcore_colden as hardcore_colden1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
from elegant_tesla.cranky_goldwasser import pedantic_stonebraker as pedantic_stonebraker1
