from peaceful_bohr import gifted_boyd as gifted_boyd1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
from peaceful_bohr.zen_pike import sleepy_thompson as sleepy_thompson1
