from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
import vigorous_thompson as vigorous_thompson1
from elegant_tesla.boring_dijkstra import thirsty_kirch as thirsty_kirch1
