from peaceful_bohr import zen_curie as zen_curie1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.boring_dijkstra import distracted_hawking as distracted_hawking1
