from elegant_tesla.boring_dijkstra import hungry_poitras as hungry_poitras1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.boring_boyd import pedantic_kilby as pedantic_kilby1
