from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from elegant_tesla.boring_dijkstra import awesome_mccarthy as awesome_mccarthy1
from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from elegant_tesla.boring_dijkstra import hungry_poitras as hungry_poitras1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
from elegant_tesla.reverent_nightingale import awesome_mccarthy as awesome_mccarthy2
from elegant_tesla.reverent_goldwasser import awesome_mccarthy as awesome_mccarthy3
