from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from elegant_tesla.youthful_booth import youthful_booth as youthful_booth1
from elegant_tesla.boring_boyd.clever_raman import determined_ptolemy as determined_ptolemy1
from elegant_tesla.zen_pike import thirsty_knuth as thirsty_knuth1
from elegant_tesla.boring_boyd.clever_raman import zen_curie as zen_curie1
import gracious_kare as gracious_kare1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
