from peaceful_bohr.zen_pike import laughing_feynman as laughing_feynman1
from peaceful_bohr.zen_pike import flamboyant_mcclintock as flamboyant_mcclintock1
from stupefied_gates import quirky_sammet as quirky_sammet1
