from peaceful_bohr.zen_pike import gracious_rosalind as gracious_rosalind1
from elegant_tesla.zen_pike.optimistic_hawking import mystifying_mayer as mystifying_mayer1
from elegant_tesla.boring_dijkstra import dazzling_nightingale as dazzling_nightingale1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
