from elegant_tesla.zen_pike import ecstatic_goldberg as ecstatic_goldberg1
from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from elegant_tesla.zen_pike import thirsty_knuth as thirsty_knuth1
from peaceful_bohr.zen_pike import elated_leavitt as elated_leavitt1
from elegant_tesla.boring_dijkstra import suspicious_meitner as suspicious_meitner1
import gracious_kare as gracious_kare1
from elegant_tesla.boring_dijkstra import festive_hodgkin as festive_hodgkin1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
