from elegant_tesla.youthful_booth import boring_dijkstra as boring_dijkstra1
from elegant_tesla.youthful_booth import youthful_booth as youthful_booth1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
from elegant_tesla.boring_boyd import zen_pike as zen_pike1
