from elegant_tesla.reverent_nightingale import mystifying_brahmagupta as mystifying_brahmagupta1
from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from stupefied_gates import quirky_sammet as quirky_sammet1
