from peaceful_bohr.eloquent_liskov.vibrant_northcutt import focused_mirzakhani as focused_mirzakhani1
import vigorous_thompson as vigorous_thompson1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani2
from elegant_tesla.vibrant_northcutt import friendly_goodall as friendly_goodall1
