from loving_visvesvaraya.confident_hoover.boring_dijkstra import focused_kilby as focused_kilby1
from loving_visvesvaraya.confident_hoover.boring_dijkstra import mystifying_goodall as mystifying_goodall1
from loving_visvesvaraya.confident_hoover.boring_dijkstra import lucid_pike as lucid_pike1
