import peaceful_turing as peaceful_turing1
from loving_visvesvaraya.confident_hoover.boring_dijkstra import focused_kilby as focused_kilby1
from loving_visvesvaraya.confident_hoover.determined_ptolemy import determined_curran as determined_curran1
from loving_visvesvaraya.confident_hoover.boring_dijkstra import mystifying_goodall as mystifying_goodall1
from loving_visvesvaraya.confident_hoover.brave_nobel import practical_joliot as practical_joliot1
