from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
import vigorous_thompson as vigorous_thompson1
from loving_visvesvaraya.upbeat_nightingale import eager_johnson as eager_johnson1
from loving_visvesvaraya.upbeat_nightingale import epic_khorana as epic_khorana1
