from loving_visvesvaraya.upbeat_nightingale import nifty_babbage as nifty_babbage1
import vigorous_thompson as vigorous_thompson1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
