import stoic_keller as stoic_keller1
from elegant_tesla.amazing_fermi import boring_dijkstra as boring_dijkstra1
import hardcore_shaw as hardcore_shaw1
from elegant_tesla.amazing_fermi import priceless_dijkstra as priceless_dijkstra1
from elegant_tesla.amazing_fermi import silly_easley as silly_easley1
