from elegant_tesla.heuristic_babbage import boring_dijkstra as boring_dijkstra1
from elegant_tesla.boring_dijkstra.optimistic_hawking import sleepy_euclid as sleepy_euclid1
from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
