from elegant_tesla.cranky_goldwasser import distracted_meitner as distracted_meitner1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
from elegant_tesla.boring_dijkstra import confident_hoover as confident_hoover1
from elegant_tesla.boring_dijkstra.optimistic_hawking import stupefied_kirch as stupefied_kirch1
from elegant_tesla.boring_dijkstra import zen_pike as zen_pike1
from elegant_tesla.cranky_goldwasser import infallible_easley as infallible_easley1
