from elegant_tesla.cranky_goldwasser import distracted_meitner as distracted_meitner1
from elegant_tesla.boring_dijkstra import zen_curie as zen_curie1
from elegant_tesla.boring_dijkstra import epic_hamilton as epic_hamilton1
from elegant_tesla.zen_pike.optimistic_hawking import trusting_banach as trusting_banach1
from elegant_tesla.trusting_banach import laughing_brattain as laughing_brattain1
from elegant_tesla.zen_pike import hungry_mahavira as hungry_mahavira1
