from elegant_tesla.cranky_goldwasser import distracted_meitner as distracted_meitner1
from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from elegant_tesla.boring_dijkstra import festive_hodgkin as festive_hodgkin1
from elegant_tesla.boring_dijkstra import zen_pike as zen_pike1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
