from elegant_tesla.cranky_goldwasser import distracted_meitner as distracted_meitner1
from stupefied_gates import quirky_sammet as quirky_sammet1
from elegant_tesla.zen_pike import tender_heisenberg as tender_heisenberg1
