from elegant_tesla.boring_boyd import relaxed_einstein as relaxed_einstein1
from elegant_tesla.zen_pike import hardcore_morse as hardcore_morse1
from elegant_tesla.boring_boyd import zen_pike as zen_pike1
from elegant_tesla.reverent_goldwasser import eager_williams as eager_williams1
