from elegant_tesla.cranky_goldwasser import distracted_meitner as distracted_meitner1
from elegant_tesla.cranky_goldwasser import wizardly_curran as wizardly_curran1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
from elegant_tesla.boring_dijkstra import friendly_hodgkin as friendly_hodgkin1
