from elegant_tesla.cranky_goldwasser import distracted_meitner as distracted_meitner1
from elegant_tesla.zen_pike import priceless_shannon as priceless_shannon1
from elegant_tesla.boring_dijkstra import goofy_swanson as goofy_swanson1
