from elegant_tesla.boring_dijkstra import objective_lamarr as objective_lamarr1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
from elegant_tesla.boring_dijkstra import zen_pike as zen_pike1
