from elegant_tesla.cranky_goldwasser import distracted_meitner as distracted_meitner1
from stupefied_gates import quirky_sammet as quirky_sammet1
from elegant_tesla.cranky_goldwasser.competent_benz import cocky_poincare as cocky_poincare1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
