from elegant_tesla.cranky_goldwasser import distracted_meitner as distracted_meitner1
from elegant_tesla.zen_pike.optimistic_hawking import cranky_goldwasser as cranky_goldwasser1
from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from elegant_tesla.cranky_goldwasser import zen_pike as zen_pike1
