from elegant_tesla.cranky_goldwasser import zen_pike as zen_pike1
from elegant_tesla.boring_dijkstra import epic_ptolemy as epic_ptolemy1
from elegant_tesla.zen_pike import thirsty_knuth as thirsty_knuth1
import cranky_swanson as cranky_swanson1
from elegant_tesla.cranky_goldwasser import distracted_meitner as distracted_meitner1
from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
from elegant_tesla.boring_dijkstra.optimistic_hawking import tender_ptolemy as tender_ptolemy1
