from elegant_tesla.cranky_goldwasser import distracted_meitner as distracted_meitner1
from elegant_tesla.reverent_goldwasser.goofy_kepler import dreamy_mayer as dreamy_mayer1
from elegant_tesla.zen_pike.optimistic_hawking.laughing_feynman import youthful_kowalevski as youthful_kowalevski1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
from elegant_tesla.boring_dijkstra.optimistic_hawking import elegant_tesla as elegant_tesla1
