from elegant_tesla.nostalgic_wozniak.cranky_goldwasser.sharp_sinoussi import hardcore_hopper as hardcore_hopper1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.zen_pike.optimistic_hawking.laughing_feynman import mystifying_goldwasser as mystifying_goldwasser1
from peaceful_bohr import zen_curie as zen_curie1
from elegant_tesla.zen_pike.optimistic_hawking import cranky_goldwasser as cranky_goldwasser1
import vigorous_thompson as vigorous_thompson1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
from elegant_tesla.youthful_booth import stupefied_montalcini as stupefied_montalcini1
