from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.nostalgic_wozniak.cranky_goldwasser.sharp_sinoussi import peaceful_tesla as peaceful_tesla1
from elegant_tesla.youthful_booth import stupefied_montalcini as stupefied_montalcini1
