from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.nostalgic_wozniak.cranky_goldwasser.sharp_sinoussi import heuristic_babbage as heuristic_babbage1
from elegant_tesla.nostalgic_wozniak.boring_dijkstra.mystifying_volhard import heuristic_babbage as heuristic_babbage2
