from elegant_tesla.boring_dijkstra.optimistic_hawking.goofy_kepler import suspicious_meninsky as suspicious_meninsky1
from elegant_tesla.reverent_goldwasser.frosty_jackson.brave_hopper import wizardly_payne as wizardly_payne1
from elegant_tesla.reverent_goldwasser.goofy_kepler import loving_varahamihira as loving_varahamihira1
from elegant_tesla.boring_boyd import zen_curie as zen_curie1
