from elegant_tesla.boring_dijkstra import zen_curie as zen_curie1
from elegant_tesla.boring_boyd import zen_curie as zen_curie2
from elegant_tesla.boring_dijkstra.optimistic_hawking import elegant_tesla as elegant_tesla1
from elegant_tesla.boring_dijkstra.optimistic_hawking.laughing_feynman import stupefied_hawking as stupefied_hawking1
