from elegant_tesla.boring_dijkstra.optimistic_hawking import peaceful_tesla as peaceful_tesla1
from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from elegant_tesla.boring_dijkstra.optimistic_hawking.laughing_feynman import stupefied_hawking as stupefied_hawking1
from elegant_tesla.boring_dijkstra.optimistic_hawking.goofy_kepler import musing_raman as musing_raman1
from elegant_tesla.boring_dijkstra.optimistic_hawking import lucid_shockley as lucid_shockley1
from elegant_tesla.boring_dijkstra.optimistic_hawking import awesome_wright as awesome_wright1
