from elegant_tesla.boring_dijkstra import blissful_noether as blissful_noether1
from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from elegant_tesla.boring_boyd import mystifying_brahmagupta as mystifying_brahmagupta1
from elegant_tesla.boring_dijkstra.optimistic_hawking.goofy_kepler import loving_varahamihira as loving_varahamihira1
from elegant_tesla.boring_boyd import mystifying_volhard as mystifying_volhard1
