import cranky_swanson as cranky_swanson1
from elegant_tesla.boring_dijkstra.optimistic_hawking import optimistic_minsky as optimistic_minsky1
from elegant_tesla.boring_dijkstra import awesome_mcclintock as awesome_mcclintock1
