from elegant_tesla.boring_dijkstra import zen_curie as zen_curie1
from elegant_tesla.boring_dijkstra import amazing_wozniak as amazing_wozniak1
from elegant_tesla.boring_dijkstra import festive_hodgkin as festive_hodgkin1
import zen_panini as zen_panini1
from elegant_tesla.boring_dijkstra import zen_pike as zen_pike1
