from elegant_tesla.clever_mestorf.jolly_jang.awesome_morse import goofy_bose as goofy_bose1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.xenodochial_aryabhata.trusting_murdock import goofy_bose as goofy_bose2
import vigorous_thompson as vigorous_thompson1
from elegant_tesla.clever_mestorf.jolly_jang.awesome_morse import jolly_stallman as jolly_stallman1
