from elegant_tesla.romantic_lovelace import romantic_lovelace as romantic_lovelace1
from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
