import gracious_bhaskara as gracious_bhaskara1
import amazing_shirley as amazing_shirley1
from elegant_tesla.boring_dijkstra import distracted_hawking as distracted_hawking1
from elegant_tesla.boring_dijkstra import zen_pike as zen_pike1
from elegant_tesla.boring_dijkstra.optimistic_hawking import elastic_nobel as elastic_nobel1
