from elegant_tesla.boring_boyd.zealous_kowalevski import zen_curie as zen_curie1
from elegant_tesla.boring_boyd import pedantic_jones as pedantic_jones1
from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
import amazing_shirley as amazing_shirley1
import cocky_pike as cocky_pike1
from elegant_tesla.boring_boyd import relaxed_einstein as relaxed_einstein1
from stupefied_gates import nervous_fermat as nervous_fermat1
from elegant_tesla.boring_boyd import nervous_ardinghelli as nervous_ardinghelli1
from elegant_tesla.mystifying_euclid import dazzling_mirzakhani as dazzling_mirzakhani1
