from elegant_tesla.boring_boyd import hungry_johnson as hungry_johnson1
from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from elegant_tesla.mystifying_euclid import dazzling_mirzakhani as dazzling_mirzakhani1
