from elegant_tesla.cranky_goldwasser import boring_edison as boring_edison1
import vigorous_thompson as vigorous_thompson1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.cranky_goldwasser import jolly_lalande as jolly_lalande1
