from elegant_tesla.reverent_goldwasser.frosty_jackson.goofy_archimedes import wizardly_payne as wizardly_payne1
from elegant_tesla.boring_dijkstra import festive_hodgkin as festive_hodgkin1
from elegant_tesla.boring_dijkstra import friendly_hodgkin as friendly_hodgkin1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
