from elegant_tesla.zen_pike.festive_hopper import pedantic_heyrovsky as pedantic_heyrovsky1
from elegant_tesla.zen_pike.festive_hopper import ecstatic_fermat as ecstatic_fermat1
from elegant_tesla.zen_pike.festive_hopper import optimistic_hawking as optimistic_hawking1
