from peaceful_bohr.eloquent_liskov.xenodochial_aryabhata import elated_leavitt as elated_leavitt1
from elegant_tesla.boring_dijkstra.optimistic_hawking import inspiring_mirzakhani as inspiring_mirzakhani1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
import vigorous_thompson as vigorous_thompson1
from elegant_tesla.xenodochial_aryabhata import awesome_morse as awesome_morse1
