from elegant_tesla.reverent_goldwasser.zealous_yonath import infallible_aryabhata as infallible_aryabhata1
import vigorous_thompson as vigorous_thompson1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
