import loving_jepsen as loving_jepsen1
from elegant_tesla.zen_pike.cocky_goldstine import cranky_ramanujan as cranky_ramanujan1
from elegant_tesla.heuristic_babbage.agitated_hoover import lucid_pike as lucid_pike1
from elegant_tesla.heuristic_babbage.agitated_hoover import zen_pike as zen_pike1
from stupefied_gates import jovial_benz as jovial_benz1
