from elegant_tesla.silly_payne import romantic_jepsen as romantic_jepsen1
import vigorous_thompson as vigorous_thompson1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.boring_dijkstra import reverent_swartz as reverent_swartz1
