from elegant_tesla.zen_pike.optimistic_hawking.goofy_kepler import affectionate_wing as affectionate_wing1
from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
