from elegant_tesla.boring_dijkstra import zen_curie as zen_curie1
from elegant_tesla.boring_boyd import zen_curie as zen_curie2
from elegant_tesla.trusting_banach import elegant_bell as elegant_bell1
from elegant_tesla.zen_pike.optimistic_hawking import trusting_banach as trusting_banach1
