from elegant_tesla.pedantic_bhabha.objective_northcutt import goofy_bose as goofy_bose1
from elegant_tesla.zen_pike.optimistic_hawking import trusting_banach as trusting_banach1
from elegant_tesla.trusting_banach import laughing_brattain as laughing_brattain1
