from loving_visvesvaraya.confident_hoover import infallible_joliot as infallible_joliot1
from loving_visvesvaraya.confident_hoover.peaceful_bohr import jovial_archimedes as jovial_archimedes1
from loving_visvesvaraya.confident_hoover.peaceful_bohr import nostalgic_lovelace as nostalgic_lovelace1
from loving_visvesvaraya.confident_hoover.determined_ptolemy import condescending_engelbart as condescending_engelbart1
from loving_visvesvaraya.confident_hoover.boring_dijkstra import ecstatic_kepler as ecstatic_kepler1
from loving_visvesvaraya.confident_hoover.kind_morse.hungry_euclid import inspiring_wiles as inspiring_wiles1
from loving_visvesvaraya.confident_hoover.boring_dijkstra import focused_kilby as focused_kilby1
from loving_visvesvaraya.confident_hoover.determined_ptolemy import friendly_davinci as friendly_davinci1
from loving_visvesvaraya.confident_hoover.boring_dijkstra import lucid_pike as lucid_pike1
from loving_visvesvaraya.confident_hoover.kind_morse.hungry_euclid import hungry_euclid as hungry_euclid1
from loving_visvesvaraya.confident_hoover.kind_morse.jovial_clarke import hardcore_carson as hardcore_carson1
from loving_visvesvaraya.confident_hoover.kind_morse.jovial_clarke import jovial_clarke as jovial_clarke1
import vigorous_thompson as vigorous_thompson1
from loving_visvesvaraya.confident_hoover.determined_ptolemy import affectionate_turing as affectionate_turing1
