from loving_visvesvaraya.confident_hoover.boring_dijkstra import angry_borg as angry_borg1
from loving_visvesvaraya.confident_hoover.boring_dijkstra import xenodochial_goodall as xenodochial_goodall1
import vigorous_thompson as vigorous_thompson1
from loving_visvesvaraya.confident_hoover.peaceful_bohr import nostalgic_lovelace as nostalgic_lovelace1
from loving_visvesvaraya.confident_hoover.determined_ptolemy import condescending_engelbart as condescending_engelbart1
