from elegant_tesla.boring_dijkstra.agitated_goldberg import quirky_cori as quirky_cori1
from elegant_tesla.vibrant_northcutt.goofy_kepler.agitated_goldberg import youthful_wescoff as youthful_wescoff1
import cocky_pike as cocky_pike1
from elegant_tesla.boring_dijkstra.agitated_goldberg import clever_yonath as clever_yonath1
from elegant_tesla.boring_dijkstra.agitated_goldberg import optimistic_hawking as optimistic_hawking1
from elegant_tesla.boring_dijkstra.agitated_goldberg import festive_minsky as festive_minsky1
