from elegant_tesla.vibrant_northcutt.goofy_kepler import elastic_gates as elastic_gates1
from elegant_tesla.vibrant_northcutt import vibrant_goldberg as vibrant_goldberg1
from elegant_tesla.boring_boyd import mystifying_brahmagupta as mystifying_brahmagupta1
from elegant_tesla.vibrant_northcutt import zen_curie as zen_curie1
