from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
from peaceful_bohr.zen_pike import inspiring_babbage as inspiring_babbage1
from peaceful_bohr.admiring_carson.vibrant_northcutt import focused_mirzakhani as focused_mirzakhani2
from peaceful_bohr.admiring_carson.vibrant_northcutt.quirky_davinci import focused_mirzakhani as focused_mirzakhani3
