from elegant_tesla.upbeat_raman import objective_mcnulty as objective_mcnulty1
from elegant_tesla.boring_dijkstra import zen_pike as zen_pike1
from elegant_tesla.boring_dijkstra import distracted_hawking as distracted_hawking1
import reverent_goldwasser as reverent_goldwasser1
