from loving_visvesvaraya.confident_hoover.kind_morse.clever_yonath import cranky_noyce as cranky_noyce1
from loving_visvesvaraya.confident_hoover.boring_dijkstra import focused_kilby as focused_kilby1
from loving_visvesvaraya.confident_hoover.boring_dijkstra import blissful_bhaskara as blissful_bhaskara1
from loving_visvesvaraya.confident_hoover.kind_morse.clever_yonath import zen_pike as zen_pike1
from loving_visvesvaraya.confident_hoover.boring_dijkstra import jovial_agnesi as jovial_agnesi1
from loving_visvesvaraya.confident_hoover.determined_ptolemy import condescending_engelbart as condescending_engelbart1
from loving_visvesvaraya.confident_hoover.boring_dijkstra import gallant_bartik as gallant_bartik1
