from loving_visvesvaraya.confident_hoover.boring_dijkstra import xenodochial_goodall as xenodochial_goodall1
from loving_visvesvaraya.confident_hoover.determined_ptolemy import condescending_engelbart as condescending_engelbart1
