from elegant_tesla.cranky_goldwasser import infallible_jepsen as infallible_jepsen1
from elegant_tesla.boring_dijkstra import suspicious_meitner as suspicious_meitner1
from elegant_tesla.cranky_goldwasser import zen_pike as zen_pike1
