from peaceful_bohr.naughty_wright import relaxed_shirley as relaxed_shirley1
from elegant_tesla.youthful_booth import youthful_booth as youthful_booth1
from peaceful_bohr.zen_pike import nifty_yonath as nifty_yonath1
from elegant_tesla.zen_pike import thirsty_knuth as thirsty_knuth1
from elegant_tesla.zen_pike.optimistic_hawking.goofy_kepler import silly_goodall as silly_goodall1
from peaceful_bohr.naughty_wright import focused_mirzakhani as focused_mirzakhani1
import vigorous_thompson as vigorous_thompson1
from peaceful_bohr.friendly_lalande import zealous_yalow as zealous_yalow1
from peaceful_bohr import stoic_feynman as stoic_feynman1
