from elegant_tesla.boring_boyd import zen_pike as zen_pike1
from elegant_tesla.jovial_kirch import jovial_kirch as jovial_kirch1
from elegant_tesla.boring_boyd import mystifying_brahmagupta as mystifying_brahmagupta1
