from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
from peaceful_bohr.zen_pike import goofy_kepler as goofy_kepler1
from elegant_tesla.clever_mestorf import optimistic_lamarr as optimistic_lamarr1
import amazing_shirley as amazing_shirley1
from peaceful_bohr.admiring_carson.clever_mestorf import focused_mirzakhani as focused_mirzakhani2
