from peaceful_bohr.admiring_carson.clever_mestorf import focused_mirzakhani as focused_mirzakhani1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani2
from peaceful_bohr.admiring_carson.clever_mestorf import zen_curie as zen_curie1
from peaceful_bohr.admiring_carson.clever_mestorf import eloquent_nightingale as eloquent_nightingale1
