from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
import amazing_shirley as amazing_shirley1
from elegant_tesla.boring_dijkstra import zen_pike as zen_pike1
from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from peaceful_bohr.admiring_carson.clever_mestorf import focused_mirzakhani as focused_mirzakhani2
