from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
import amazing_shirley as amazing_shirley1
from peaceful_bohr.admiring_carson.clever_mestorf import focused_mirzakhani as focused_mirzakhani2
from elegant_tesla.boring_dijkstra import festive_hodgkin as festive_hodgkin1
from elegant_tesla.clever_mestorf import festive_hodgkin as festive_hodgkin2
