from elegant_tesla.zen_pike import focused_bhaskara as focused_bhaskara1
from peaceful_bohr.admiring_carson.clever_mestorf import focused_mirzakhani as focused_mirzakhani1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani2
