from elegant_tesla.xenodochial_aryabhata import modest_mccarthy as modest_mccarthy1
import peaceful_kowalevski as peaceful_kowalevski1
from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from elegant_tesla.boring_boyd import zen_pike as zen_pike1
import reverent_goldwasser as reverent_goldwasser1
