from elegant_tesla.xenodochial_aryabhata import gracious_banach as gracious_banach1
from elegant_tesla.zen_pike import loving_pare as loving_pare1
from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
