from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
import amazing_shirley as amazing_shirley1
from elegant_tesla.boring_boyd import hungry_johnson as hungry_johnson1
from elegant_tesla.boring_boyd.clever_raman import zen_curie as zen_curie1
from elegant_tesla.boring_boyd import relaxed_einstein as relaxed_einstein1
from elegant_tesla.boring_boyd.clever_raman import vigorous_albattani as vigorous_albattani1
