from stupefied_gates import nervous_fermat as nervous_fermat1
from elegant_tesla.boring_boyd.stupefied_kirch import serene_colden as serene_colden1
from elegant_tesla.boring_boyd.clever_raman.laughing_brattain import flamboyant_ardinghelli as flamboyant_ardinghelli1
from elegant_tesla.boring_boyd.clever_raman import zen_curie as zen_curie1
