import hungry_neumann as hungry_neumann1
from elegant_tesla.nostalgic_wozniak.cranky_goldwasser.confident_hoover import unruffled_hoover as unruffled_hoover1
from elegant_tesla.nostalgic_wozniak.cranky_goldwasser.sharp_sinoussi import nifty_murdock as nifty_murdock1
from elegant_tesla.nostalgic_wozniak.boring_dijkstra import admiring_mirzakhani as admiring_mirzakhani1
