from elegant_tesla.nostalgic_wozniak.cranky_goldwasser.confident_hoover import unruffled_hoover as unruffled_hoover1
import hungry_neumann as hungry_neumann1
from elegant_tesla.nostalgic_wozniak.boring_dijkstra import angry_pasteur as angry_pasteur1
