from elegant_tesla.boring_dijkstra import zen_curie as zen_curie1
from elegant_tesla.zen_pike.optimistic_hawking.laughing_feynman import zealous_varahamihira as zealous_varahamihira1
from elegant_tesla.boring_dijkstra.optimistic_hawking import confident_khorana as confident_khorana1
