import vigorous_thompson as vigorous_thompson1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
from loving_visvesvaraya import vigorous_goodall as vigorous_goodall1
