from loving_visvesvaraya import trusting_shockley as trusting_shockley1
import vigorous_thompson as vigorous_thompson1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
