from peaceful_bohr.eloquent_liskov.vibrant_northcutt import focused_mirzakhani as focused_mirzakhani1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani2
from elegant_tesla.vibrant_northcutt.practical_colden import determined_lichterman as determined_lichterman1
import vigorous_thompson as vigorous_thompson1
