from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from elegant_tesla.youthful_booth import youthful_booth as youthful_booth1
from elegant_tesla.boring_boyd import nervous_ardinghelli as nervous_ardinghelli1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
from elegant_tesla.zen_pike.optimistic_hawking import pedantic_clarke as pedantic_clarke1
