from peaceful_bohr.brave_dubinsky import hardcore_agnesi as hardcore_agnesi1
from elegant_tesla.zen_pike import compassionate_rosalind as compassionate_rosalind1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
