from peaceful_bohr.zen_pike import laughing_feynman as laughing_feynman1
from stupefied_gates import quirky_sammet as quirky_sammet1
import sleepy_shannon as sleepy_shannon1
import vigorous_thompson as vigorous_thompson1
from elegant_tesla.boring_boyd import wizardly_kirch as wizardly_kirch1
from elegant_tesla.boring_dijkstra import goofy_swanson as goofy_swanson1
