from elegant_tesla.reverent_goldwasser.goofy_kepler import frosty_mcclintock as frosty_mcclintock1
from elegant_tesla.zen_pike import thirsty_knuth as thirsty_knuth1
from peaceful_bohr.zen_pike import goofy_kepler as goofy_kepler1
from peaceful_bohr.zen_pike import gracious_rosalind as gracious_rosalind1
import vigorous_franklin as vigorous_franklin1
import gracious_kare as gracious_kare1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
