from elegant_tesla.boring_boyd import nervous_ardinghelli as nervous_ardinghelli1
from elegant_tesla.boring_boyd import focused_bohr as focused_bohr1
from elegant_tesla.boring_boyd import mystifying_brahmagupta as mystifying_brahmagupta1
