from elegant_tesla.boring_dijkstra.agitated_goldberg import quirky_cori as quirky_cori1
from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from elegant_tesla.boring_dijkstra.agitated_goldberg import romantic_euclid as romantic_euclid1
from elegant_tesla.boring_boyd.agitated_goldberg import youthful_wescoff as youthful_wescoff1
from elegant_tesla.boring_boyd.agitated_goldberg import festive_hodgkin as festive_hodgkin1
from elegant_tesla.boring_dijkstra.agitated_goldberg import optimistic_hawking as optimistic_hawking1
