from elegant_tesla.vibrant_northcutt.goofy_kepler.loving_varahamihira import zen_curie as zen_curie1
from elegant_tesla.vibrant_northcutt.goofy_kepler.loving_varahamihira import optimistic_hawking as optimistic_hawking1
