from elegant_tesla.boring_dijkstra import zen_curie as zen_curie1
from elegant_tesla.heuristic_babbage import boring_dijkstra as boring_dijkstra1
import silly_haibt as silly_haibt1
from elegant_tesla.heuristic_babbage import thirsty_kalam as thirsty_kalam1
from elegant_tesla.heuristic_babbage.dazzling_shaw import priceless_austin as priceless_austin1
import nostalgic_dijkstra as nostalgic_dijkstra1
import silly_goldwasser as silly_goldwasser1
import compassionate_mcclintock as compassionate_mcclintock1
from elegant_tesla.boring_boyd import zen_pike as zen_pike1
import wonderful_ptolemy as wonderful_ptolemy1
