from elegant_tesla.vibrant_northcutt.goofy_kepler.silly_goodall import upbeat_ramanujan as upbeat_ramanujan1
from elegant_tesla.vibrant_northcutt import unruffled_bartik as unruffled_bartik1
from elegant_tesla.boring_dijkstra import quizzical_shaw as quizzical_shaw1
from elegant_tesla.boring_dijkstra import zen_pike as zen_pike1
import vigorous_thompson as vigorous_thompson1
from elegant_tesla.vibrant_northcutt.goofy_kepler.silly_goodall import goofy_bose as goofy_bose1
from elegant_tesla.vibrant_northcutt.goofy_kepler import goofy_bose as goofy_bose2
