from peaceful_bohr.brave_dubinsky import jolly_austin as jolly_austin1
from elegant_tesla.loving_bohr import lucid_poincare as lucid_poincare1
from elegant_tesla.zen_pike.optimistic_hawking import cranky_lamport as cranky_lamport1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
from peaceful_bohr.friendly_lalande import trusting_poitras as trusting_poitras1
from peaceful_bohr.zen_pike.relaxed_thompson import laughing_cray as laughing_cray1
from elegant_tesla.boring_dijkstra import festive_dijkstra as festive_dijkstra1
from elegant_tesla.boring_boyd import zen_curie as zen_curie1
import vigorous_thompson as vigorous_thompson1
from elegant_tesla.reverent_nightingale.vigorous_stallman.cranky_ramanujan.relaxed_bhaskara import jolly_austin as jolly_austin2
from elegant_tesla.boring_boyd import silly_hoover as silly_hoover1
