from elegant_tesla.cranky_goldwasser.competent_benz.goofy_liskov import loving_varahamihira as loving_varahamihira1
from elegant_tesla.cranky_goldwasser.competent_benz.goofy_liskov import youthful_bartik as youthful_bartik1
