from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from elegant_tesla.cranky_goldwasser.competent_benz import boring_dijkstra as boring_dijkstra1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
