from elegant_tesla.mystifying_euclid.loving_varahamihira import mystifying_blackwell as mystifying_blackwell1
from elegant_tesla.mystifying_euclid import mystifying_euclid as mystifying_euclid1
from elegant_tesla.mystifying_euclid import unruffled_bardeen as unruffled_bardeen1
from elegant_tesla.mystifying_euclid.relaxed_kepler import mystifying_blackwell as mystifying_blackwell2
from elegant_tesla.mystifying_euclid.loving_varahamihira import gifted_borg as gifted_borg1
from elegant_tesla.mystifying_euclid.loving_varahamihira import relaxed_neumann as relaxed_neumann1
