from elegant_tesla.mystifying_euclid import fervent_franklin as fervent_franklin1
from elegant_tesla.boring_boyd import hungry_johnson as hungry_johnson1
from elegant_tesla.mystifying_euclid import dazzling_mirzakhani as dazzling_mirzakhani1
