from elegant_tesla.boring_boyd.zealous_kowalevski import zen_curie as zen_curie1
from peaceful_bohr.eloquent_liskov.vibrant_northcutt import focused_mirzakhani as focused_mirzakhani1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani2
from elegant_tesla.vibrant_northcutt.goofy_kepler.loving_varahamihira import optimistic_hawking as optimistic_hawking1
from elegant_tesla.vibrant_northcutt.goofy_kepler.loving_varahamihira import unruffled_yonath as unruffled_yonath1
from elegant_tesla.boring_boyd.zealous_kowalevski import optimistic_hawking as optimistic_hawking2
