from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from elegant_tesla.boring_boyd import zen_pike as zen_pike1
from elegant_tesla.boring_dijkstra import zen_pike as zen_pike2
from elegant_tesla.boring_dijkstra import suspicious_meitner as suspicious_meitner1
from elegant_tesla.boring_dijkstra import festive_hodgkin as festive_hodgkin1
from elegant_tesla.boring_boyd import pensive_mcnulty as pensive_mcnulty1
import sad_thompson as sad_thompson1
