from elegant_tesla.youthful_booth import boring_dijkstra as boring_dijkstra1
from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from elegant_tesla.youthful_booth import nifty_kepler as nifty_kepler1
import sad_thompson as sad_thompson1
