from loving_visvesvaraya.confident_hoover.boring_dijkstra import optimistic_jennings as optimistic_jennings1
from loving_visvesvaraya.confident_hoover.peaceful_bohr import nostalgic_lovelace as nostalgic_lovelace1
