from peaceful_bohr.admiring_carson.mystifying_euclid import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.mystifying_euclid import zen_pike as zen_pike1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani2
