from peaceful_bohr.admiring_carson.youthful_booth import focused_mirzakhani as focused_mirzakhani1
from peaceful_bohr.admiring_carson.youthful_booth.kind_khorana import focused_mirzakhani as focused_mirzakhani2
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani3
from peaceful_bohr.admiring_carson.youthful_booth.kind_khorana import trusting_williams as trusting_williams1
