from peaceful_bohr.admiring_carson.youthful_booth import focused_mirzakhani as focused_mirzakhani1
from peaceful_bohr.admiring_carson.youthful_booth.kind_khorana import focused_mirzakhani as focused_mirzakhani2
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani3
from peaceful_bohr.admiring_carson.youthful_booth.kind_khorana import trusting_williams as trusting_williams1
from peaceful_bohr.admiring_carson.youthful_booth.kind_khorana import optimistic_hawking as optimistic_hawking1
import vigorous_thompson as vigorous_thompson1
import sad_thompson as sad_thompson1
