from peaceful_bohr import zen_curie as zen_curie1
import condescending_franklin as condescending_franklin1
from elegant_tesla.zen_pike import hopeful_ritchie as hopeful_ritchie1
from peaceful_bohr.zen_pike import gracious_rosalind as gracious_rosalind1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
