from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
from elegant_tesla.reverent_goldwasser.goofy_kepler import optimistic_einstein as optimistic_einstein1
