from elegant_tesla.zen_pike.optimistic_hawking import zealous_yonath as zealous_yonath1
from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.reverent_goldwasser.zealous_yonath import dreamy_turing as dreamy_turing1
from peaceful_bohr.admiring_carson import zen_curie as zen_curie1
from elegant_tesla.boring_dijkstra.optimistic_hawking.heuristic_babbage import zealous_yonath as zealous_yonath2
import vigorous_thompson as vigorous_thompson1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
from elegant_tesla.youthful_booth import stupefied_montalcini as stupefied_montalcini1
