from peaceful_bohr.naughty_wright import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.youthful_booth import youthful_booth as youthful_booth1
import vigorous_thompson as vigorous_thompson1
from peaceful_bohr.friendly_lalande import objective_perlman as objective_perlman1
