from elegant_tesla.boring_boyd import mystifying_brahmagupta as mystifying_brahmagupta1
from elegant_tesla.boring_boyd.stupefied_kirch import serene_colden as serene_colden1
from elegant_tesla.boring_boyd.stupefied_kirch import friendly_bartik as friendly_bartik1
