from elegant_tesla.boring_boyd import relaxed_einstein as relaxed_einstein1
from elegant_tesla.boring_boyd import hungry_johnson as hungry_johnson1
from elegant_tesla.boring_boyd.clever_raman import zen_curie as zen_curie1
