from elegant_tesla.boring_boyd.stupefied_kirch import nervous_hypatia as nervous_hypatia1
from elegant_tesla.boring_boyd import mystifying_brahmagupta as mystifying_brahmagupta1
from elegant_tesla.boring_boyd.stupefied_kirch import friendly_bartik as friendly_bartik1
