from peaceful_bohr.eloquent_liskov.vibrant_northcutt import focused_mirzakhani as focused_mirzakhani1
from peaceful_bohr.eloquent_liskov.vibrant_northcutt.hopeful_spence import focused_mirzakhani as focused_mirzakhani2
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani3
