from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from elegant_tesla.reverent_goldwasser.eloquent_borg import eloquent_borg as eloquent_borg1
from elegant_tesla.boring_dijkstra import zen_pike as zen_pike1
from elegant_tesla.boring_dijkstra.optimistic_hawking.heuristic_babbage import happy_poincare as happy_poincare1
from elegant_tesla.cranky_goldwasser.hopeful_feynman import zen_curie as zen_curie1
