from elegant_tesla.reverent_nightingale.pensive_montalcini import awesome_lichterman as awesome_lichterman1
from elegant_tesla.reverent_nightingale.pensive_montalcini import confident_poitras as confident_poitras1
from elegant_tesla.boring_dijkstra.optimistic_hawking.heuristic_babbage import happy_poincare as happy_poincare1
from elegant_tesla.zen_pike.optimistic_hawking.heuristic_babbage import dazzling_shaw as dazzling_shaw1
from elegant_tesla.cranky_goldwasser.hopeful_feynman import zen_curie as zen_curie1
from elegant_tesla.boring_dijkstra import suspicious_meitner as suspicious_meitner1
from elegant_tesla.cranky_goldwasser.hopeful_feynman import romantic_poitras as romantic_poitras1
