from peaceful_bohr.admiring_carson.youthful_booth import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani2
from elegant_tesla.boring_dijkstra import zen_pike as zen_pike1
from elegant_tesla.boring_boyd import zen_curie as zen_curie1
