from peaceful_bohr.admiring_carson.youthful_booth import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani2
from elegant_tesla.youthful_booth import stupefied_montalcini as stupefied_montalcini1
