from zealous_knuth.zealous_knuth import quirky_fermi as quirky_fermi1
from zealous_knuth.zealous_knuth import infallible_joliot as infallible_joliot1
from zealous_knuth.zealous_knuth import confident_hoover as confident_hoover1
from zealous_knuth.zealous_knuth import stoic_yalow as stoic_yalow1
