from elegant_tesla.zen_pike.cocky_goldstine import cranky_ramanujan as cranky_ramanujan1
from elegant_tesla.boring_dijkstra import zen_pike as zen_pike1
from elegant_tesla.boring_boyd import nervous_ardinghelli as nervous_ardinghelli1
from elegant_tesla.reverent_nightingale import mystifying_brahmagupta as mystifying_brahmagupta1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
