from elegant_tesla.clever_mestorf.vigorous_colden.distracted_aryabhata import goofy_bose as goofy_bose1
from elegant_tesla.clever_mestorf.vigorous_colden.distracted_aryabhata import zen_curie as zen_curie1
