from elegant_tesla.reverent_goldwasser.goofy_kepler import zen_curie as zen_curie1
from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from elegant_tesla.reverent_goldwasser.goofy_kepler import youthful_bartik as youthful_bartik1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
