import vigorous_thompson as vigorous_thompson1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.reverent_goldwasser.goofy_kepler import goofy_bose as goofy_bose1
