from elegant_tesla.reverent_goldwasser.goofy_kepler import zen_curie as zen_curie1
from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.reverent_goldwasser.goofy_kepler import quirky_davinci as quirky_davinci1
from elegant_tesla.boring_dijkstra import friendly_hodgkin as friendly_hodgkin1
from elegant_tesla.boring_dijkstra import quirky_davinci as quirky_davinci2
