from elegant_tesla.cranky_goldwasser.boring_agnesi import compassionate_lalande as compassionate_lalande1
import vigorous_thompson as vigorous_thompson1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
