from elegant_tesla.cranky_goldwasser.boring_agnesi import nervous_mestorf as nervous_mestorf1
import modest_kirch as modest_kirch1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
