from elegant_tesla.cranky_goldwasser import quirky_lewin as quirky_lewin1
from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.vibrant_northcutt.amazing_hoover import kind_engelbart as kind_engelbart1
import vigorous_thompson as vigorous_thompson1
