from elegant_tesla.cranky_goldwasser import determined_yalow as determined_yalow1
import vigorous_thompson as vigorous_thompson1
from elegant_tesla.cranky_goldwasser.nostalgic_sinoussi import musing_cray as musing_cray1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
