from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
from elegant_tesla.boring_dijkstra.optimistic_hawking.laughing_feynman import jolly_volhard as jolly_volhard1
from elegant_tesla.pedantic_bhabha.objective_northcutt import goofy_bose as goofy_bose1
