from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
import dazzling_dijkstra as dazzling_dijkstra1
import amazing_shirley as amazing_shirley1
from elegant_tesla.boring_boyd import zen_pike as zen_pike1
import gifted_johnson as gifted_johnson1
