import silly_panini as silly_panini1
from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from elegant_tesla.boring_boyd import mystifying_brahmagupta as mystifying_brahmagupta1
from elegant_tesla.boring_boyd import zen_pike as zen_pike1
from elegant_tesla.boring_boyd import infallible_kowalevski as infallible_kowalevski1
import sad_thompson as sad_thompson1
