import sleepy_shannon as sleepy_shannon1
from elegant_tesla.boring_boyd import mystifying_brahmagupta as mystifying_brahmagupta1
from elegant_tesla.boring_boyd import zen_pike as zen_pike1
from elegant_tesla.boring_boyd import pedantic_kilby as pedantic_kilby1
