from peaceful_bohr.naughty_wright import nervous_johnson as nervous_johnson1
from peaceful_bohr.zen_pike import laughing_feynman as laughing_feynman1
from elegant_tesla.youthful_booth import youthful_booth as youthful_booth1
from elegant_tesla.vibrant_northcutt.goofy_kepler.dreamy_mayer import boring_mestorf as boring_mestorf1
from peaceful_bohr.friendly_lalande import unruffled_hodgkin as unruffled_hodgkin1
from peaceful_bohr.naughty_wright import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
from peaceful_bohr.brave_dubinsky import zen_murdock as zen_murdock1
from peaceful_bohr.naughty_wright import relaxed_shirley as relaxed_shirley1
from elegant_tesla.boring_dijkstra.optimistic_hawking import sleepy_euclid as sleepy_euclid1
from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from peaceful_bohr.zen_pike import sleepy_euclid as sleepy_euclid2
from elegant_tesla.zen_pike import thirsty_knuth as thirsty_knuth1
from peaceful_bohr.zen_pike import gracious_rosalind as gracious_rosalind1
import vigorous_thompson as vigorous_thompson1
from stupefied_gates import quirky_sammet as quirky_sammet1
import sad_thompson as sad_thompson1
