from peaceful_bohr.naughty_wright import nervous_johnson as nervous_johnson1
from peaceful_bohr.naughty_wright import relaxed_shirley as relaxed_shirley1
from elegant_tesla.youthful_booth import youthful_booth as youthful_booth1
from peaceful_bohr.zen_pike import gracious_rosalind as gracious_rosalind1
from peaceful_bohr.friendly_lalande import unruffled_hodgkin as unruffled_hodgkin1
from elegant_tesla.boring_dijkstra.optimistic_hawking import festive_hopper as festive_hopper1
from peaceful_bohr import zen_curie as zen_curie1
from peaceful_bohr.naughty_wright import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.boring_dijkstra import friendly_hodgkin as friendly_hodgkin1
import sad_thompson as sad_thompson1
