from elegant_tesla.boring_boyd import zen_pike as zen_pike1
from elegant_tesla.priceless_visvesvaraya import priceless_visvesvaraya as priceless_visvesvaraya1
from elegant_tesla.boring_boyd import mystifying_brahmagupta as mystifying_brahmagupta1
