from elegant_tesla.priceless_visvesvaraya import nervous_boyd as nervous_boyd1
from elegant_tesla.priceless_visvesvaraya import loving_darwin as loving_darwin1
from elegant_tesla.boring_boyd import hungry_johnson as hungry_johnson1
from elegant_tesla.boring_boyd.clever_raman import zen_curie as zen_curie1
from elegant_tesla.boring_boyd import relaxed_einstein as relaxed_einstein1
from elegant_tesla.boring_boyd.clever_raman import youthful_bhabha as youthful_bhabha1
from elegant_tesla.boring_boyd.clever_raman import vigorous_albattani as vigorous_albattani1
from elegant_tesla.boring_boyd.stupefied_kirch import loving_yonath as loving_yonath1
