from elegant_tesla.boring_boyd import suspicious_meitner as suspicious_meitner1
from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
import gracious_kare as gracious_kare1
from elegant_tesla.boring_dijkstra import quizzical_shaw as quizzical_shaw1
