from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
from elegant_tesla.zen_pike import loving_pare as loving_pare1
from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
