from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from elegant_tesla.zen_pike import thirsty_knuth as thirsty_knuth1
import amazing_shirley as amazing_shirley1
from elegant_tesla.boring_boyd import hungry_johnson as hungry_johnson1
from elegant_tesla.reverent_goldwasser import pensive_fermat as pensive_fermat1
from elegant_tesla.zen_pike import hungry_mahavira as hungry_mahavira1
from elegant_tesla.zen_pike import sad_wing as sad_wing1
from elegant_tesla.boring_boyd import focused_bohr as focused_bohr1
from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from elegant_tesla.boring_dijkstra import festive_hodgkin as festive_hodgkin1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
