from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from elegant_tesla.zen_pike.gracious_tesla import zen_curie as zen_curie1
import amazing_shirley as amazing_shirley1
from elegant_tesla.zen_pike.optimistic_hawking import festive_hopper as festive_hopper1
from elegant_tesla.zen_pike import pedantic_lichterman as pedantic_lichterman1
from elegant_tesla.boring_boyd import pedantic_jennings as pedantic_jennings1
from elegant_tesla.boring_dijkstra import festive_hodgkin as festive_hodgkin1
from elegant_tesla.youthful_booth import stupefied_montalcini as stupefied_montalcini1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
