from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from elegant_tesla.boring_dijkstra import festive_hodgkin as festive_hodgkin1
from elegant_tesla.boring_dijkstra.optimistic_hawking import silly_allen as silly_allen1
from elegant_tesla.boring_dijkstra import zen_pike as zen_pike1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
