from elegant_tesla.zen_pike import ecstatic_goldberg as ecstatic_goldberg1
from elegant_tesla.boring_boyd import mystifying_brahmagupta as mystifying_brahmagupta1
from elegant_tesla.zen_pike import zealous_cray as zealous_cray1
from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from elegant_tesla.boring_dijkstra import festive_hodgkin as festive_hodgkin1
from elegant_tesla.youthful_booth import stupefied_montalcini as stupefied_montalcini1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
