from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
from elegant_tesla.zen_pike.optimistic_hawking import reverent_mahavira as reverent_mahavira1
from elegant_tesla.boring_dijkstra import zen_pike as zen_pike1
