from elegant_tesla.boring_dijkstra import epic_hamilton as epic_hamilton1
from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
import jovial_swartz as jovial_swartz1
