from elegant_tesla.zen_pike.optimistic_hawking import eloquent_neumann as eloquent_neumann1
from elegant_tesla.zen_pike import thirsty_knuth as thirsty_knuth1
from elegant_tesla.boring_dijkstra.optimistic_hawking import awesome_wright as awesome_wright1
import lucid_jackson as lucid_jackson1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
