from elegant_tesla.boring_boyd import focused_bohr as focused_bohr1
from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from elegant_tesla.boring_boyd import nervous_ardinghelli as nervous_ardinghelli1
