from elegant_tesla.zen_pike import ecstatic_goldberg as ecstatic_goldberg1
from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from elegant_tesla.boring_boyd import mystifying_brahmagupta as mystifying_brahmagupta1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
