from peaceful_bohr.goofy_varahamihira import condescending_minsky as condescending_minsky1
from elegant_tesla.zen_pike import cocky_borg as cocky_borg1
import vigorous_thompson as vigorous_thompson1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
