from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.zen_pike import loving_pare as loving_pare1
from elegant_tesla.boring_boyd import zen_curie as zen_curie1
import vigorous_thompson as vigorous_thompson1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
