from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from elegant_tesla.heuristic_babbage.mystifying_blackwell.agitated_hoover.blissful_hypatia import youthful_wescoff as youthful_wescoff1
from elegant_tesla.heuristic_babbage.mystifying_blackwell.agitated_hoover import zen_curie as zen_curie2
