from elegant_tesla.boring_dijkstra import modest_fermi as modest_fermi1
from elegant_tesla.vibrant_northcutt.practical_colden import practical_colden as practical_colden1
from elegant_tesla.vibrant_northcutt import goofy_bose as goofy_bose1
from elegant_tesla.vibrant_northcutt.goofy_kepler import goofy_bose as goofy_bose2
