from elegant_tesla.vibrant_northcutt import vibrant_goldberg as vibrant_goldberg1
from elegant_tesla.vibrant_northcutt import zen_curie as zen_curie1
import amazing_shirley as amazing_shirley1
from elegant_tesla.vibrant_northcutt import unruffled_bartik as unruffled_bartik1
from elegant_tesla.boring_boyd import pedantic_jennings as pedantic_jennings1
from elegant_tesla.boring_dijkstra.optimistic_hawking import dazzling_dijkstra as dazzling_dijkstra1
