from elegant_tesla.vibrant_northcutt import goofy_bose as goofy_bose1
from elegant_tesla.vibrant_northcutt import unruffled_bartik as unruffled_bartik1
from elegant_tesla.boring_dijkstra import zen_pike as zen_pike1
