from elegant_tesla.vibrant_northcutt import unruffled_bartik as unruffled_bartik1
from elegant_tesla.boring_dijkstra.optimistic_hawking.goofy_kepler import suspicious_meninsky as suspicious_meninsky1
from elegant_tesla.boring_dijkstra import trusting_bohr as trusting_bohr1
