import gracious_bhaskara as gracious_bhaskara1
from stupefied_gates import nervous_fermat as nervous_fermat1
from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from elegant_tesla.boring_boyd import mystifying_brahmagupta as mystifying_brahmagupta1
from elegant_tesla.boring_boyd import mystifying_volhard as mystifying_volhard1
