from elegant_tesla.reverent_nightingale.zen_bohr import zen_curie as zen_curie1
from elegant_tesla.boring_boyd import zen_curie as zen_curie2
from elegant_tesla.boring_dijkstra import friendly_hodgkin as friendly_hodgkin1
from elegant_tesla.boring_dijkstra.agitated_goldberg import xenodochial_noether as xenodochial_noether1
