from elegant_tesla.reverent_nightingale.zen_bohr import zen_curie as zen_curie1
from elegant_tesla.boring_dijkstra.optimistic_hawking.goofy_kepler import loving_varahamihira as loving_varahamihira1
from elegant_tesla.reverent_nightingale.zen_bohr import zen_pike as zen_pike1
from elegant_tesla.boring_boyd import zen_curie as zen_curie2
from elegant_tesla.boring_dijkstra import friendly_hodgkin as friendly_hodgkin1
from elegant_tesla.zen_pike import zealous_liskov as zealous_liskov1
