import tender_rosalind as tender_rosalind1
from priceless_stonebraker.quizzical_hamilton.happy_poitras import mystifying_sammet as mystifying_sammet1
import gallant_yonath as gallant_yonath1
import focused_liskov as focused_liskov1
