from elegant_tesla.cranky_goldwasser import zen_pike as zen_pike1
from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from elegant_tesla.zen_pike import thirsty_knuth as thirsty_knuth1
from elegant_tesla.boring_dijkstra import suspicious_meitner as suspicious_meitner1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
