from elegant_tesla.nostalgic_wozniak.boring_dijkstra.mystifying_volhard import nifty_brattain as nifty_brattain1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
import vigorous_thompson as vigorous_thompson1
