from peaceful_bohr.brave_dubinsky import loving_varahamihira as loving_varahamihira1
from peaceful_bohr import zen_curie as zen_curie1
from peaceful_bohr.brave_dubinsky import silly_allen as silly_allen1
import vigorous_thompson as vigorous_thompson1
from elegant_tesla.jovial_kirch import jovial_kirch as jovial_kirch1
