from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
from peaceful_bohr.admiring_carson.vibrant_northcutt import focused_mirzakhani as focused_mirzakhani2
from peaceful_bohr.zen_pike import trusting_montalcini as trusting_montalcini1
from peaceful_bohr.brave_dubinsky import silly_allen as silly_allen1
from elegant_tesla.vibrant_northcutt.goofy_kepler.agitated_goldberg import cranky_williams as cranky_williams1
import vigorous_thompson as vigorous_thompson1
from stupefied_gates import loving_feynman as loving_feynman1
