import hungry_mirzakhani as hungry_mirzakhani1
from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from elegant_tesla.heuristic_babbage.hopeful_swartz import lucid_pike as lucid_pike1
from elegant_tesla.boring_dijkstra import friendly_hodgkin as friendly_hodgkin1
