from peaceful_bohr.naughty_wright import relaxed_shirley as relaxed_shirley1
from peaceful_bohr.friendly_lalande import nervous_beaver as nervous_beaver1
from elegant_tesla.youthful_booth import youthful_booth as youthful_booth1
import heuristic_roentgen as heuristic_roentgen1
from peaceful_bohr.naughty_wright import focused_mirzakhani as focused_mirzakhani1
from peaceful_bohr.brave_dubinsky import jolly_borg as jolly_borg1
import vigorous_thompson as vigorous_thompson1
from peaceful_bohr.cranky_mahavira import relaxed_bhaskara as relaxed_bhaskara1
from peaceful_bohr.naughty_wright.youthful_bartik import focused_mirzakhani as focused_mirzakhani2
