import reverent_fermi as reverent_fermi1
from elegant_tesla.reverent_goldwasser.eloquent_borg import eloquent_borg as eloquent_borg1
import vigorous_thompson as vigorous_thompson1
from elegant_tesla.reverent_goldwasser.eloquent_borg import nifty_kepler as nifty_kepler1
