from elegant_tesla.boring_dijkstra import silly_kirch as silly_kirch1
from elegant_tesla.boring_dijkstra.agitated_goldberg import romantic_euclid as romantic_euclid1
from elegant_tesla.boring_boyd.agitated_goldberg import stupefied_lovelace as stupefied_lovelace1
from elegant_tesla.boring_dijkstra import romantic_euclid as romantic_euclid2
from elegant_tesla.boring_dijkstra.agitated_goldberg import optimistic_hawking as optimistic_hawking1
from elegant_tesla.boring_dijkstra import friendly_hodgkin as friendly_hodgkin1
