from elegant_tesla.boring_dijkstra.agitated_goldberg import quirky_cori as quirky_cori1
from elegant_tesla.boring_dijkstra import optimistic_poitras as optimistic_poitras1
from elegant_tesla.boring_dijkstra.agitated_goldberg import romantic_euclid as romantic_euclid1
from elegant_tesla.boring_boyd.agitated_goldberg import youthful_wescoff as youthful_wescoff1
from elegant_tesla.boring_boyd import hungry_johnson as hungry_johnson1
from elegant_tesla.boring_dijkstra.agitated_goldberg import clever_yonath as clever_yonath1
from elegant_tesla.boring_dijkstra.agitated_goldberg import optimistic_hawking as optimistic_hawking1
from elegant_tesla.boring_dijkstra.agitated_goldberg import festive_minsky as festive_minsky1
