from elegant_tesla.zen_pike.gracious_tesla import zen_curie as zen_curie1
from elegant_tesla.zen_pike.gracious_tesla import wizardly_payne as wizardly_payne1
from elegant_tesla.zen_pike.optimistic_hawking import festive_hopper as festive_hopper1
from elegant_tesla.zen_pike.optimistic_hawking import pedantic_clarke as pedantic_clarke1
from elegant_tesla.boring_dijkstra import festive_hodgkin as festive_hodgkin1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
