from stupefied_gates import nervous_fermat as nervous_fermat1
from elegant_tesla.boring_dijkstra.optimistic_hawking import inspiring_mirzakhani as inspiring_mirzakhani1
from elegant_tesla.boring_dijkstra.optimistic_hawking.laughing_feynman import jolly_volhard as jolly_volhard1
from elegant_tesla.xenodochial_aryabhata import awesome_morse as awesome_morse1
from elegant_tesla.xenodochial_aryabhata import kind_hopper as kind_hopper1
