from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from elegant_tesla.reverent_goldwasser.goofy_kepler import goofy_bose as goofy_bose1
from elegant_tesla.zen_pike import thirsty_knuth as thirsty_knuth1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
from elegant_tesla.reverent_goldwasser.goofy_kepler import optimistic_hawking as optimistic_hawking1
