from elegant_tesla.xenodochial_aryabhata.clever_raman import determined_tesla as determined_tesla1
from elegant_tesla.xenodochial_aryabhata.clever_raman import inspiring_feynman as inspiring_feynman1
