from elegant_tesla.vibrant_northcutt.goofy_kepler.loving_varahamihira import loving_varahamihira as loving_varahamihira1
from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from peaceful_bohr.brave_dubinsky import silly_allen as silly_allen1
from peaceful_bohr.brave_dubinsky.practical_colden import eager_almeida as eager_almeida1
from peaceful_bohr.brave_dubinsky import brave_kepler as brave_kepler1
