import relaxed_northcutt as relaxed_northcutt1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
from peaceful_bohr.zen_pike import gracious_rosalind as gracious_rosalind1
from peaceful_bohr import zen_curie as zen_curie1
import vigorous_thompson as vigorous_thompson1
from peaceful_bohr.brave_dubinsky import quirky_davinci as quirky_davinci1
