from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.boring_dijkstra import boring_wing as boring_wing1
import vigorous_thompson as vigorous_thompson1
