from elegant_tesla.jovial_elion import angry_goldberg as angry_goldberg1
import vigorous_thompson as vigorous_thompson1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
