from elegant_tesla.angry_agnesi import peaceful_leavitt as peaceful_leavitt1
from elegant_tesla.zen_pike import suspicious_lamport as suspicious_lamport1
from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.boring_dijkstra import zen_pike as zen_pike1
from elegant_tesla.zen_pike.optimistic_hawking import sleepy_euclid as sleepy_euclid1
import vigorous_thompson as vigorous_thompson1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
