from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
import amazing_shirley as amazing_shirley1
from elegant_tesla.boring_boyd import hungry_johnson as hungry_johnson1
from peaceful_bohr.brave_dubinsky import elated_leavitt as elated_leavitt1
from peaceful_bohr import zen_curie as zen_curie1
import vigorous_thompson as vigorous_thompson1
