from elegant_tesla.boring_boyd import relaxed_einstein as relaxed_einstein1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
import vigorous_thompson as vigorous_thompson1
