from elegant_tesla.youthful_booth import youthful_booth as youthful_booth1
from peaceful_bohr.admiring_carson import competent_bohr as competent_bohr1
from elegant_tesla.zen_pike import thirsty_knuth as thirsty_knuth1
from elegant_tesla.zen_pike import frosty_mccarthy as frosty_mccarthy1
import vigorous_thompson as vigorous_thompson1
