from elegant_tesla.boring_dijkstra import objective_lamarr as objective_lamarr1
from elegant_tesla.boring_dijkstra import zen_curie as zen_curie1
from elegant_tesla.boring_dijkstra import epic_hamilton as epic_hamilton1
import vigorous_thompson as vigorous_thompson1
