from peaceful_bohr.brave_dubinsky import vibrant_mirzakhani as vibrant_mirzakhani1
import relaxed_northcutt as relaxed_northcutt1
from stupefied_gates import loving_mcnulty as loving_mcnulty1
from stupefied_gates import nervous_fermat as nervous_fermat1
