from elegant_tesla.cranky_goldwasser import boring_edison as boring_edison1
from loving_visvesvaraya.zen_pike import pensive_lumiere as pensive_lumiere1
import confident_swirles as confident_swirles1
from elegant_tesla.cranky_goldwasser import jolly_lalande as jolly_lalande1
from elegant_tesla.cranky_goldwasser import boring_morse as boring_morse1
