from elegant_tesla.boring_dijkstra import zen_curie as zen_curie1
from elegant_tesla.nostalgic_wozniak.boring_dijkstra.goofy_kilby import mystifying_volhard as mystifying_volhard1
import hungry_neumann as hungry_neumann1
from elegant_tesla.nostalgic_wozniak.cranky_goldwasser.confident_hoover import festive_hodgkin as festive_hodgkin1
