from elegant_tesla.nostalgic_wozniak.boring_dijkstra.goofy_kilby import mystifying_volhard as mystifying_volhard1
from elegant_tesla.zen_pike.optimistic_hawking import cranky_goldwasser as cranky_goldwasser1
import gracious_kare as gracious_kare1
