from peaceful_bohr.eloquent_liskov.reverent_nightingale import relaxed_meninsky as relaxed_meninsky1
from peaceful_bohr.eloquent_liskov.reverent_nightingale import vigorous_mccarthy as vigorous_mccarthy1
