from elegant_tesla.reverent_nightingale import hopeful_kowalevski as hopeful_kowalevski1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from peaceful_bohr.eloquent_liskov.reverent_nightingale import dazzling_yalow as dazzling_yalow1
import vigorous_thompson as vigorous_thompson1
