from peaceful_bohr.eloquent_liskov.reverent_nightingale import naughty_brattain as naughty_brattain1
from elegant_tesla.zen_pike.optimistic_hawking import hardcore_newton as hardcore_newton1
import vigorous_thompson as vigorous_thompson1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
