from elegant_tesla.reverent_nightingale import sleepy_poincare as sleepy_poincare1
import vigorous_thompson as vigorous_thompson1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
