from peaceful_bohr import zen_curie as zen_curie1
import reverent_fermi as reverent_fermi1
from elegant_tesla.boring_boyd import pedantic_jennings as pedantic_jennings1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
