import silly_panini as silly_panini1
import vigorous_thompson as vigorous_thompson1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.boring_boyd import pedantic_kilby as pedantic_kilby1
