from peaceful_bohr import zen_curie as zen_curie1
import vigorous_thompson as vigorous_thompson1
from peaceful_bohr.brave_dubinsky.mystifying_euclid import stupefied_archimedes as stupefied_archimedes1
from peaceful_bohr.brave_dubinsky import stupefied_archimedes as stupefied_archimedes2
