from elegant_tesla.vibrant_northcutt.practical_colden import eloquent_liskov as eloquent_liskov1
from elegant_tesla.vibrant_northcutt.practical_colden import goofy_swanson as goofy_swanson1
from elegant_tesla.vibrant_northcutt.practical_colden import relaxed_bhaskara as relaxed_bhaskara1
