from elegant_tesla.vibrant_northcutt.practical_colden import eloquent_liskov as eloquent_liskov1
from elegant_tesla.vibrant_northcutt import stoic_wescoff as stoic_wescoff1
from elegant_tesla.vibrant_northcutt.practical_colden import epic_khorana as epic_khorana1
