from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from elegant_tesla.zen_pike import thirsty_knuth as thirsty_knuth1
from elegant_tesla.zen_pike.wizardly_meitner import wizardly_meitner as wizardly_meitner1
from stupefied_gates import agitated_chandrasekhar as agitated_chandrasekhar1
import gallant_lalande as gallant_lalande1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
