from elegant_tesla.boring_boyd import relaxed_einstein as relaxed_einstein1
from elegant_tesla.cranky_goldwasser import boring_edison as boring_edison1
from elegant_tesla.cranky_goldwasser import festive_mclean as festive_mclean1
from loving_visvesvaraya.zen_pike import pensive_lumiere as pensive_lumiere1
from elegant_tesla.cranky_goldwasser import boring_morse as boring_morse1
