from peaceful_bohr.admiring_carson.mystifying_euclid import focused_mirzakhani as focused_mirzakhani1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani2
from peaceful_bohr.jovial_bell import cranky_raman as cranky_raman1
from peaceful_bohr.admiring_carson.mystifying_euclid.loving_varahamihira import focused_mirzakhani as focused_mirzakhani3
