from elegant_tesla.boring_dijkstra import zen_curie as zen_curie1
from elegant_tesla.zen_pike import loving_pare as loving_pare1
from elegant_tesla.zen_pike.optimistic_hawking.laughing_feynman import romantic_hypatia as romantic_hypatia1
