from elegant_tesla.zen_pike.optimistic_hawking.laughing_feynman import infallible_aryabhata as infallible_aryabhata1
from elegant_tesla.youthful_booth import youthful_booth as youthful_booth1
from elegant_tesla.zen_pike.optimistic_hawking.laughing_feynman import agitated_hoover as agitated_hoover1
from elegant_tesla.zen_pike.optimistic_hawking.laughing_feynman import dazzling_shaw as dazzling_shaw1
from elegant_tesla.zen_pike.optimistic_hawking.laughing_feynman import romantic_hypatia as romantic_hypatia1
