from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.clever_mestorf import peaceful_brattain as peaceful_brattain1
from elegant_tesla.clever_mestorf import gracious_bassi as gracious_bassi1
