from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.zen_pike.optimistic_hawking.heuristic_babbage import zen_brahmagupta as zen_brahmagupta1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
