from elegant_tesla.reverent_nightingale import wizardly_payne as wizardly_payne1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
