from elegant_tesla.boring_dijkstra import zen_pike as zen_pike1
from elegant_tesla.youthful_booth import youthful_booth as youthful_booth1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
