from elegant_tesla.reverent_nightingale import wonderful_wilson as wonderful_wilson1
from elegant_tesla.youthful_booth import boring_dijkstra as boring_dijkstra1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
