from elegant_tesla.youthful_booth import youthful_booth as youthful_booth1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
from peaceful_bohr import zen_curie as zen_curie1
from peaceful_bohr.admiring_carson import zen_curie as zen_curie2
from elegant_tesla.reverent_nightingale import competent_bose as competent_bose1
from elegant_tesla.boring_boyd import zen_pike as zen_pike1
