from elegant_tesla.tender_heisenberg import optimistic_cray as optimistic_cray1
from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from elegant_tesla.boring_dijkstra import stoic_wescoff as stoic_wescoff1
from elegant_tesla.boring_dijkstra.optimistic_hawking import awesome_wiles as awesome_wiles1
