from elegant_tesla.vibrant_northcutt.goofy_kepler import elastic_gates as elastic_gates1
from stupefied_gates import nervous_fermat as nervous_fermat1
from elegant_tesla.boring_boyd.clever_raman import determined_ptolemy as determined_ptolemy1
