from elegant_tesla.boring_boyd.clever_raman import determined_ptolemy as determined_ptolemy1
from elegant_tesla.vibrant_northcutt.goofy_kepler.clever_raman import heuristic_cori as heuristic_cori1
from elegant_tesla.vibrant_northcutt.goofy_kepler.clever_raman import elegant_leavitt as elegant_leavitt1
