from elegant_tesla.boring_dijkstra import optimistic_einstein as optimistic_einstein1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.zen_pike import admiring_knuth as admiring_knuth1
import vigorous_thompson as vigorous_thompson1
from elegant_tesla.cranky_goldwasser import modest_curie as modest_curie1
