from elegant_tesla.youthful_booth import youthful_booth as youthful_booth1
from elegant_tesla.zen_pike import thirsty_knuth as thirsty_knuth1
from elegant_tesla.cranky_goldwasser import trusting_curie as trusting_curie1
import vigorous_thompson as vigorous_thompson1
from elegant_tesla.cranky_goldwasser import confident_hoover as confident_hoover1
