from elegant_tesla.cranky_goldwasser import sleepy_montalcini as sleepy_montalcini1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.cranky_goldwasser import distracted_meitner as distracted_meitner1
from elegant_tesla.cranky_goldwasser import trusting_curie as trusting_curie1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
from elegant_tesla.reverent_goldwasser import eager_williams as eager_williams1
