from peaceful_bohr.eloquent_liskov.vibrant_northcutt import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.vibrant_northcutt.goofy_kepler.clever_raman import ecstatic_khorana as ecstatic_khorana1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani2
import gracious_kare as gracious_kare1
