import reverent_fermi as reverent_fermi1
import pedantic_mclean as pedantic_mclean1
from elegant_tesla.silly_payne import romantic_jepsen as romantic_jepsen1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
