from elegant_tesla.youthful_booth import youthful_booth as youthful_booth1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
import vigorous_thompson as vigorous_thompson1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
from peaceful_bohr.jovial_bell import dreamy_mclean as dreamy_mclean1
