from loving_visvesvaraya.confident_hoover.relaxed_spence import musing_fermi as musing_fermi1
import objective_mahavira as objective_mahavira1
from loving_visvesvaraya.confident_hoover.peaceful_bohr import nostalgic_lovelace as nostalgic_lovelace1
import vigorous_thompson as vigorous_thompson1
