from loving_visvesvaraya.confident_hoover.relaxed_spence import nostalgic_ardinghelli as nostalgic_ardinghelli1
from loving_visvesvaraya.confident_hoover.peaceful_bohr import nostalgic_lovelace as nostalgic_lovelace1
import vigorous_thompson as vigorous_thompson1
