from loving_visvesvaraya.confident_hoover.relaxed_spence import dreamy_lewin as dreamy_lewin1
from loving_visvesvaraya.confident_hoover.relaxed_spence import boring_noyce as boring_noyce1
from loving_visvesvaraya.confident_hoover.peaceful_bohr import nostalgic_lovelace as nostalgic_lovelace1
import vigorous_thompson as vigorous_thompson1
