from loving_visvesvaraya.confident_hoover.relaxed_spence import modest_bartik as modest_bartik1
from loving_visvesvaraya.confident_hoover.peaceful_bohr import nostalgic_lovelace as nostalgic_lovelace1
import vigorous_thompson as vigorous_thompson1
