from elegant_tesla.youthful_booth import youthful_booth as youthful_booth1
from elegant_tesla.zen_pike import thirsty_knuth as thirsty_knuth1
from elegant_tesla.zen_pike.cranky_tesla import zen_pike as zen_pike1
from elegant_tesla.zen_pike.cranky_tesla import mystifying_volhard as mystifying_volhard1
from elegant_tesla.zen_pike.cranky_tesla import gifted_yonath as gifted_yonath1
from elegant_tesla.boring_boyd import focused_bohr as focused_bohr1
from elegant_tesla.zen_pike import gracious_bassi as gracious_bassi1
