from elegant_tesla.zen_pike.cocky_goldstine import compassionate_visvesvaraya as compassionate_visvesvaraya1
from elegant_tesla.zen_pike.cocky_goldstine import kind_bardeen as kind_bardeen1
from stupefied_gates import nervous_fermat as nervous_fermat1
from elegant_tesla.zen_pike.cocky_goldstine import competent_brahmagupta as competent_brahmagupta1
from elegant_tesla.zen_pike.cocky_goldstine import suspicious_franklin as suspicious_franklin1
from elegant_tesla.zen_pike.cocky_goldstine import wizardly_wilson as wizardly_wilson1
