from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.zen_pike.festive_mclean import gifted_hermann as gifted_hermann1
from peaceful_bohr.zen_pike import inspiring_feynman as inspiring_feynman1
