from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from elegant_tesla.boring_boyd import nervous_ardinghelli as nervous_ardinghelli1
from elegant_tesla.youthful_booth import stupefied_montalcini as stupefied_montalcini1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
