from elegant_tesla.clever_mestorf.agitated_goldberg import quizzical_blackwell as quizzical_blackwell1
from elegant_tesla.boring_dijkstra.agitated_goldberg import wizardly_jepsen as wizardly_jepsen1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
