from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from elegant_tesla.reverent_nightingale.pensive_montalcini import eloquent_yonath as eloquent_yonath1
from elegant_tesla.reverent_nightingale.pensive_montalcini import infallible_aryabhata as infallible_aryabhata1
from elegant_tesla.heuristic_babbage.infallible_aryabhata import lucid_pike as lucid_pike1
from elegant_tesla.reverent_nightingale.flamboyant_euler import zen_curie as zen_curie1
from elegant_tesla.boring_dijkstra.optimistic_hawking.heuristic_babbage import infallible_aryabhata as infallible_aryabhata2
