from elegant_tesla.boring_boyd.agitated_goldberg import youthful_wescoff as youthful_wescoff1
from elegant_tesla.boring_boyd import hungry_johnson as hungry_johnson1
from elegant_tesla.boring_boyd.agitated_goldberg import festive_hodgkin as festive_hodgkin1
from elegant_tesla.boring_boyd.agitated_goldberg import stupefied_lovelace as stupefied_lovelace1
