from loving_visvesvaraya.confident_hoover.boring_dijkstra import competent_yonath as competent_yonath1
from loving_visvesvaraya.confident_hoover.kind_morse.pedantic_albattani import zen_pike as zen_pike1
from loving_visvesvaraya.confident_hoover.kind_morse.pedantic_albattani import nifty_benz as nifty_benz1
