from elegant_tesla.reverent_nightingale import wonderful_wilson as wonderful_wilson1
from elegant_tesla.reverent_nightingale.nervous_ride import zen_pike as zen_pike1
from elegant_tesla.boring_boyd import elated_darwin as elated_darwin1
from peaceful_bohr.brave_dubinsky import stupefied_archimedes as stupefied_archimedes1
from peaceful_bohr.jovial_bell import unruffled_newton as unruffled_newton1
from elegant_tesla.reverent_nightingale import mystifying_ardinghelli as mystifying_ardinghelli1
import sad_thompson as sad_thompson1
