from loving_visvesvaraya.nostalgic_ardinghelli.kind_almeida import goofy_knuth as goofy_knuth1
from loving_visvesvaraya.nostalgic_ardinghelli.kind_almeida import confident_hamilton as confident_hamilton1
