from loving_visvesvaraya.nostalgic_ardinghelli.kind_almeida import goofy_mcclintock as goofy_mcclintock1
from loving_visvesvaraya.nostalgic_ardinghelli.kind_almeida import goofy_knuth as goofy_knuth1
