from modest_stonebraker.hopeful_carson import hungry_mclean as hungry_mclean1
from loving_visvesvaraya.stoic_borg import awesome_colden as awesome_colden1
from loving_visvesvaraya.stoic_borg import competent_curie as competent_curie1
from modest_stonebraker.hopeful_carson import admiring_euclid as admiring_euclid1
from loving_visvesvaraya.stoic_borg import thirsty_wright as thirsty_wright1
from modest_stonebraker.hopeful_carson import condescending_neumann as condescending_neumann1
