from modest_stonebraker.hopeful_carson import clever_brown as clever_brown1
from modest_stonebraker.hopeful_carson import hungry_northcutt as hungry_northcutt1
from stupefied_gates import nervous_fermat as nervous_fermat1
