from modest_stonebraker.hopeful_carson import clever_brown as clever_brown1
import unruffled_shannon as unruffled_shannon1
from stupefied_gates import nervous_fermat as nervous_fermat1
from modest_stonebraker.hopeful_carson import sharp_meitner as sharp_meitner1
from stupefied_gates import frosty_curran as frosty_curran1
from modest_stonebraker.hopeful_carson import epic_wiles as epic_wiles1
