from elegant_tesla.amazing_thompson import condescending_wescoff as condescending_wescoff1
from stupefied_gates import infallible_banach as infallible_banach1
import vigorous_thompson as vigorous_thompson1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
