from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from elegant_tesla.reverent_goldwasser.goofy_kepler import frosty_mcclintock as frosty_mcclintock1
from elegant_tesla.reverent_goldwasser.goofy_kepler import goofy_bose as goofy_bose1
