from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
from elegant_tesla.reverent_goldwasser.frosty_heyrovsky import boring_dijkstra as boring_dijkstra1
from elegant_tesla.reverent_goldwasser.frosty_heyrovsky import laughing_cray as laughing_cray1
