from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from elegant_tesla.boring_dijkstra.optimistic_hawking.elegant_bose import nifty_murdock as nifty_murdock1
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
from elegant_tesla.reverent_goldwasser.frosty_heyrovsky import boring_dijkstra as boring_dijkstra1
from elegant_tesla.boring_dijkstra.optimistic_hawking import tender_ptolemy as tender_ptolemy1
