from loving_visvesvaraya.confident_hoover.relaxed_spence import dreamy_lewin as dreamy_lewin1
from loving_visvesvaraya.confident_hoover.relaxed_spence import nostalgic_ardinghelli as nostalgic_ardinghelli1
from loving_visvesvaraya.confident_hoover.relaxed_spence import quirky_minsky as quirky_minsky1
from loving_visvesvaraya.confident_hoover.boring_dijkstra import focused_kilby as focused_kilby1
from loving_visvesvaraya.confident_hoover.relaxed_spence import zen_curie as zen_curie1
from loving_visvesvaraya.confident_hoover.relaxed_spence import modest_bartik as modest_bartik1
from loving_visvesvaraya import serene_lichterman as serene_lichterman1
from loving_visvesvaraya.confident_hoover.boring_dijkstra import zealous_lamport as zealous_lamport1
