from loving_visvesvaraya.confident_hoover.relaxed_spence import dreamy_lewin as dreamy_lewin1
from loving_visvesvaraya.confident_hoover.relaxed_spence import eloquent_dubinsky as eloquent_dubinsky1
from loving_visvesvaraya.confident_hoover.boring_dijkstra import focused_kilby as focused_kilby1
from loving_visvesvaraya.confident_hoover.relaxed_spence import zen_curie as zen_curie1
