from elegant_tesla.zen_pike import serene_bose as serene_bose1
from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from elegant_tesla.youthful_booth import stupefied_montalcini as stupefied_montalcini1
from elegant_tesla.zen_pike import adoring_knuth as adoring_knuth1
from elegant_tesla.zen_pike.optimistic_hawking import jovial_dijkstra as jovial_dijkstra1
from elegant_tesla.zen_pike.optimistic_hawking.laughing_feynman import friendly_panini as friendly_panini1
from elegant_tesla.boring_dijkstra import festive_hodgkin as festive_hodgkin1
from elegant_tesla.reverent_goldwasser.goofy_kepler import goofy_bose as goofy_bose1
