from elegant_tesla.boring_dijkstra import zen_curie as zen_curie1
from elegant_tesla.boring_dijkstra import festive_dijkstra as festive_dijkstra1
from elegant_tesla.boring_boyd import zen_curie as zen_curie2
from elegant_tesla.zen_pike.optimistic_hawking import hardcore_newton as hardcore_newton1
from elegant_tesla.zen_pike.optimistic_hawking.heuristic_babbage import frosty_minsky as frosty_minsky1
from elegant_tesla.zen_pike import nifty_raman as nifty_raman1
