from elegant_tesla.boring_dijkstra.optimistic_hawking.goofy_kepler import suspicious_meninsky as suspicious_meninsky1
from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
from elegant_tesla.zen_pike import naughty_turing as naughty_turing1
from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from elegant_tesla.zen_pike import loving_pare as loving_pare1
from elegant_tesla.zen_pike.optimistic_hawking.goofy_kepler import suspicious_meninsky as suspicious_meninsky2
from elegant_tesla.youthful_booth import awesome_aryabhata as awesome_aryabhata1
from elegant_tesla.youthful_booth import stupefied_montalcini as stupefied_montalcini1
