from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from elegant_tesla.boring_boyd import pedantic_jennings as pedantic_jennings1
from elegant_tesla.boring_dijkstra import festive_hodgkin as festive_hodgkin1
import lucid_jackson as lucid_jackson1
