from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from modest_stonebraker.brave_mccarthy import relaxed_shirley as relaxed_shirley1
import sad_thompson as sad_thompson1
from modest_stonebraker.brave_mccarthy import mystifying_dubinsky as mystifying_dubinsky1
