from elegant_tesla.boring_dijkstra.optimistic_hawking.goofy_kepler import youthful_bartik as youthful_bartik1
from elegant_tesla.reverent_goldwasser.youthful_bartik import thirsty_ardinghelli as thirsty_ardinghelli1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
