from zealous_knuth.peaceful_bohr import condescending_franklin as condescending_franklin1
from zealous_knuth.zealous_knuth import zen_curie as zen_curie1
from zealous_knuth.zealous_knuth import determined_ptolemy as determined_ptolemy1
from loving_visvesvaraya.stoic_borg import gallant_poitras as gallant_poitras1
from zealous_knuth.zealous_knuth import mystifying_goldwasser as mystifying_goldwasser1
