from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from elegant_tesla.confident_mclean import zen_curie as zen_curie1
import amazing_shirley as amazing_shirley1
from elegant_tesla.boring_boyd import nervous_ardinghelli as nervous_ardinghelli1
from elegant_tesla.boring_boyd.loving_varahamihira import clever_ardinghelli as clever_ardinghelli1
from stupefied_gates import infallible_keller as infallible_keller1
from elegant_tesla.mystifying_euclid import condescending_pasteur as condescending_pasteur1
from elegant_tesla.boring_boyd import zen_pike as zen_pike1
from elegant_tesla.confident_mclean import nostalgic_snyder as nostalgic_snyder1
