from loving_visvesvaraya.confident_hoover.boring_dijkstra import focused_kilby as focused_kilby1
from loving_visvesvaraya.confident_hoover.peaceful_bohr import jovial_archimedes as jovial_archimedes1
from loving_visvesvaraya.confident_hoover.determined_ptolemy import determined_curran as determined_curran1
from loving_visvesvaraya.confident_hoover.boring_dijkstra import lucid_pike as lucid_pike1
from loving_visvesvaraya.confident_hoover.peaceful_bohr import nostalgic_lovelace as nostalgic_lovelace1
from loving_visvesvaraya.confident_hoover.brave_nobel import elastic_mclean as elastic_mclean1
from loving_visvesvaraya.confident_hoover.brave_nobel import xenodochial_cori as xenodochial_cori1
from loving_visvesvaraya.confident_hoover.brave_nobel import practical_joliot as practical_joliot1
