from loving_visvesvaraya.confident_hoover.brave_nobel import nervous_edison as nervous_edison1
from loving_visvesvaraya.confident_hoover.boring_dijkstra import focused_kilby as focused_kilby1
from loving_visvesvaraya.confident_hoover.peaceful_bohr import jovial_archimedes as jovial_archimedes1
from loving_visvesvaraya.confident_hoover.boring_dijkstra import lucid_pike as lucid_pike1
from loving_visvesvaraya.confident_hoover.peaceful_bohr import nostalgic_lovelace as nostalgic_lovelace1
import vigorous_thompson as vigorous_thompson1
