from elegant_tesla.cranky_goldwasser import compassionate_stallman as compassionate_stallman1
from stupefied_gates import nervous_fermat as nervous_fermat1
import vigorous_kepler as vigorous_kepler1
from elegant_tesla.zen_pike.optimistic_hawking import objective_knuth as objective_knuth1
