from elegant_tesla.zen_pike import awesome_edison as awesome_edison1
from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from loving_visvesvaraya import serene_lichterman as serene_lichterman1
import infallible_ardinghelli as infallible_ardinghelli1
