from elegant_tesla.reverent_nightingale.pensive_montalcini import eloquent_yonath as eloquent_yonath1
from elegant_tesla.zen_pike.optimistic_hawking import frosty_goldberg as frosty_goldberg1
from elegant_tesla.boring_dijkstra.optimistic_hawking.heuristic_babbage import infallible_aryabhata as infallible_aryabhata1
from elegant_tesla.boring_dijkstra import zen_pike as zen_pike1
from elegant_tesla.reverent_nightingale.clever_blackwell import zen_curie as zen_curie1
