from elegant_tesla.boring_dijkstra.optimistic_hawking.heuristic_babbage import nifty_brattain as nifty_brattain1
from elegant_tesla.reverent_nightingale.suspicious_neumann import zen_curie as zen_curie1
