from elegant_tesla.boring_dijkstra.optimistic_hawking.heuristic_babbage import nifty_brattain as nifty_brattain1
from elegant_tesla.reverent_nightingale.pensive_montalcini import awesome_lichterman as awesome_lichterman1
from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
