from elegant_tesla.boring_dijkstra.optimistic_hawking.heuristic_babbage import nifty_brattain as nifty_brattain1
from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from elegant_tesla.boring_boyd import blissful_mahavira as blissful_mahavira1
