from loving_visvesvaraya.lucid_shockley.awesome_morse.angry_mclean import elegant_kirch as elegant_kirch1
from peaceful_bohr.admiring_carson import focused_mirzakhani as focused_mirzakhani1
from elegant_tesla.cranky_goldwasser.lucid_shockley import serene_bose as serene_bose1
from loving_visvesvaraya.lucid_shockley.awesome_morse.sad_lamarr import elegant_kirch as elegant_kirch2
from peaceful_bohr.brave_dubinsky import stupefied_archimedes as stupefied_archimedes1
