from peaceful_bohr.zen_pike import trusting_montalcini as trusting_montalcini1
import vigorous_thompson as vigorous_thompson1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
