from elegant_tesla.quirky_swirles import quirky_swirles as quirky_swirles1
from elegant_tesla.boring_boyd import zen_pike as zen_pike1
from elegant_tesla.boring_dijkstra.optimistic_hawking import awesome_wiles as awesome_wiles1
