from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from stupefied_gates import jovial_benz as jovial_benz1
from elegant_tesla.quirky_swirles import priceless_austin as priceless_austin1
from elegant_tesla.boring_dijkstra import zen_pike as zen_pike1
