from elegant_tesla.quirky_swirles import priceless_austin as priceless_austin1
from elegant_tesla.quirky_swirles import elegant_newton as elegant_newton1
from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
