from elegant_tesla.quirky_swirles.cranky_hamilton import condescending_lalande as condescending_lalande1
from elegant_tesla.quirky_swirles import elegant_newton as elegant_newton1
from elegant_tesla.quirky_swirles import priceless_austin as priceless_austin1
from elegant_tesla.quirky_swirles.cranky_hamilton import optimistic_heyrovsky as optimistic_heyrovsky1
from elegant_tesla.quirky_swirles.cranky_hamilton import condescending_euler as condescending_euler1
