import gracious_bhaskara as gracious_bhaskara1
from loving_visvesvaraya.stoic_borg import loving_neumann as loving_neumann1
from elegant_tesla.cranky_goldwasser.awesome_noyce import stoic_pike as stoic_pike1
from modest_stonebraker.sleepy_yalow import goofy_leavitt as goofy_leavitt1
from modest_stonebraker.sleepy_yalow import naughty_curie as naughty_curie1
