from elegant_tesla.boring_boyd import amazing_yalow as amazing_yalow1
import relaxed_northcutt as relaxed_northcutt1
from elegant_tesla.boring_boyd import mystifying_brahmagupta as mystifying_brahmagupta1
