from elegant_tesla.boring_boyd.zealous_kowalevski import zen_curie as zen_curie1
from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from elegant_tesla.boring_boyd.zealous_kowalevski import vigorous_albattani as vigorous_albattani1
from elegant_tesla.boring_boyd.zealous_kowalevski import optimistic_hawking as optimistic_hawking1
