from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from elegant_tesla.vibrant_northcutt.goofy_kepler.loving_varahamihira import zen_curie as zen_curie1
from elegant_tesla.vibrant_northcutt.goofy_kepler.loving_varahamihira import infallible_mirzakhani as infallible_mirzakhani1
