from stupefied_gates import nervous_fermat as nervous_fermat1
from peaceful_bohr.zen_pike.musing_fermi import lucid_pike as lucid_pike1
import gracious_kare as gracious_kare1
from elegant_tesla.vibrant_northcutt.goofy_kepler.elegant_darwin import lucid_pike as lucid_pike2
from elegant_tesla.vibrant_northcutt.goofy_kepler.elegant_darwin import boring_heisenberg as boring_heisenberg1
