import loving_jepsen as loving_jepsen1
from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from elegant_tesla.boring_dijkstra.optimistic_hawking.heuristic_babbage import happy_poincare as happy_poincare1
from elegant_tesla.reverent_nightingale.pensive_montalcini import agitated_hoover as agitated_hoover1
from elegant_tesla.reverent_nightingale.pensive_montalcini.peaceful_northcutt.lucid_shockley import goofy_bose as goofy_bose1
from stupefied_gates import nervous_fermat as nervous_fermat1
from stupefied_gates import jovial_benz as jovial_benz1
