from stupefied_gates import optimistic_einstein as optimistic_einstein1
from stupefied_gates import frosty_curran as frosty_curran1
from elegant_tesla.nostalgic_wozniak.boring_dijkstra import sad_edison as sad_edison1
from elegant_tesla.zen_pike import elegant_darwin as elegant_darwin1
from elegant_tesla.nostalgic_wozniak.boring_dijkstra import unruffled_knuth as unruffled_knuth1
from elegant_tesla.zen_pike.optimistic_hawking.laughing_feynman import hungry_hamilton as hungry_hamilton1
from stupefied_gates import stoic_jackson as stoic_jackson1
from elegant_tesla.nostalgic_wozniak.boring_dijkstra import upbeat_newton as upbeat_newton1
